### ISSUE TITLE
Async compatibility

### ISSUE THREAD

**Issue by Dennis-NL** [overextended/oxmysql#10]
Is there a alternative for "Async.parallel" and other things from mysql? Scripts like Es_extended uses this

`Async.parallel(tasks, function(results)
		local xPlayer = CreateExtendedPlayer(playerId, identifier, userData.group, userData.accounts, userData.inventory, userData.job, userData.loadout, userData.playerName, userData.coords)`

		xPlayer.getMissingAccounts(function(missingAccounts)
			if #missingAccounts > 0 then
				for k,v in ipairs(missingAccounts) do
					table.insert(xPlayer.accounts, {
						name = v,
						money = 0,
						label = Config.Accounts[v]
					})
				end

				xPlayer.createMissingAccounts(missingAccounts)
			end

			ESX.Players[playerId] = xPlayer
			TriggerEvent('esx:playerLoaded', playerId, xPlayer)

			xPlayer.triggerEvent('esx:playerLoaded', {
				identifier = xPlayer.identifier,
				money = xPlayer.getMoney(),
				accounts = xPlayer.getAccounts(),
				coords = xPlayer.getCoords(),
				inventory = xPlayer.getInventory(),
				job = xPlayer.getJob(),
				loadout = xPlayer.getLoadout(),
				money = xPlayer.getMoney(),
				maxWeight = xPlayer.maxWeight
			})

			xPlayer.triggerEvent('esx:createMissingPickups', ESX.Pickups)
		end)
	end)

**Comment by thelindat** [comment]
That function has nothing to do with mysql
