### ISSUE TITLE
Table name as Variable

### ISSUE THREAD

**Issue by eMILSOMFAN** [overextended/oxmysql#100]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the table name as a variable so it's easy for other people using my script to change the table name in the config.lua. This is the code I'm using and the error it gets.
Code:
config.lua 
TableName = "player_vehicles"

server.lua
local Table = Config.TableName 

oxmysql:
MySQL.Sync.fetchAll('SELECT * FROM ? WHERE plate = ? AND citizenid = ?', {Table, plate, pData.PlayerData.citizenid})

Error:
SCRIPT ERROR in promise (unhandled): Error: "script-name" was unable to execute a query! You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' 'player_vehicles' WHERE plate = '123456' ......
SELECT * FROMM 'player_vehicles' WHERE plate = '123456' .......

**Describe the solution you'd like**
I don't know if I'm doing something wrong or if this is not a feature. The code works if i cange the ? to player_vehicles

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by thelindat** [comment]
Just a note that _MySQL_ doesn't support table names as a variable.

You _can_ use `??` which will get parsed before sending to the server and replaced with the variable, but I would personally just format the string.

**Comment by eMILSOMFAN** [comment]
> Just a note that _MySQL_ doesn't support table names as a variable.
> 
> You _can_ use `??` which will get parsed before sending to the server and replaced with the variable, but I would personally just format the string.

Format the string how, would you please explain. Thank you :)

**Comment by thelindat** [comment]
```lua
local fetchVehicle = ('SELECT * FROM %s WHERE PLATE = ?'):format(config.vehicleTable)
MySQL.Sync.fetchAll(fetchVehicle, { plate, pData.PlayerData.citizenid })
```

**Comment by eMILSOMFAN** [comment]
> 

Thank you very much my friend, I'll try both of them and see which one I like the most :)
