### ISSUE TITLE
SCRIPT ERROR: oxmysql resource state is stopped - unable to trigger exports.oxmysql:update

### ISSUE THREAD

**Issue by Musiker15** [overextended/oxmysql#103]
After Updating from v2.1.0 to v2.1.1 this error in Server Console

```lua
SCRIPT ERROR: oxmysql resource state is stopped - unable to trigger exports.oxmysql:update
```

**Comment by thelindat** [comment]
Did you try starting the resource do that it’s state isn’t stopped, as reported?

**Comment by Musiker15** [comment]
In server.cfg `exec oxmysql`
```lua
No such config file: oxmysql
Creating script environments for oxmysql_2.1.1
Started resource oxmysql_2.1.1
[script:oxmysql_2.1.1] Database server connection established!
```

**Comment by LukeWasTakenn** [comment]
Dude you didn't even remove the version number.

**Comment by Musiker15** [comment]
I did!

**Comment by Musiker15** [comment]
Oh I think I get it. Usually I rename the old version `ScriptName_old` but with oxmysql I can't do that and I have to delete that file from server cache.

Now it works. Thank you guys for the hint :)
