### ISSUE TITLE
oxmysql error

### ISSUE THREAD

**Issue by prolol-dailo** [overextended/oxmysql#104]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Hello,
am using custom fx version but i got this error everytime i turn the server on there is any way to fix it without updating to the recommended version ?

**Screenshots**
https://prnt.sc/1s4YfK6rBAxc
**Code**
[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: Cannot find module 'node:http'
[      script:oxmysql] Require stack:
[      script:oxmysql] - C:/Users/Administrator/Desktop/Los Arabia/txData/QBCoreFramework_30BFAB.base/resources//[standalone]/oxmysql/dummy.js
[      script:oxmysql] > Function.Module (internal/modules/cjs/loader.js:794)
[      script:oxmysql] > Function.Module (internal/modules/cjs/loader.js:687)
[      script:oxmysql] > Module.require (internal/modules/cjs/loader.js:849)
[      script:oxmysql] > require (internal/modules/cjs/helpers.js:74)
[      script:oxmysql] > <unknown> (node_modules/.pnpm/node-fetch@3.2.3/node_modules/node-fetch/src/index.js (@oxmysql/dist/build.js:21441)
[      script:oxmysql] > __init (@oxmysql/dist/build.js:25)
[      script:oxmysql] > <unknown> (src/update/index.ts (@oxmysql/dist/build.js:21466)
[      script:oxmysql] > __init (@oxmysql/dist/build.js:25)
[      script:oxmysql] > <unknown> (@oxmysql/dist/build.js:21864)
[      script:oxmysql]

```lua
nothing
```

**Expected behavior**
the server work normal i think but if there is way to resolve it its gona be better

**Additional context**

**Server details**
- FXServer artifact custom version
- Operating system windiows server 2019

**Database details**
- MariaDB or MySQL 
- MariaDB 
- Version
Last recommended

**Comment by thelindat** [comment]
> am using custom fx version

Not my problem then.
