### ISSUE TITLE
Stop debuging

### ISSUE THREAD

**Issue by Fumez-DEV** [overextended/oxmysql#105]
How i stop the debuging in the console?

**Screenshots**
![image](https://user-images.githubusercontent.com/50999386/161239539-f67d9727-1683-4a46-a440-3296864f4517.png)

**Comment by Fumez-DEV** [comment]
Why you close this issue?

**Comment by Ehbw** [comment]
> Why you close this issue?
If you were to read the documentation you would see that it is on the first page.
