### ISSUE TITLE
Pterodactyl database and server IP are not the same

### ISSUE THREAD

**Issue by kenjischier** [overextended/oxmysql#106]
If the server IP and database IP is not the same oxmysql is not
![unknown](https://user-images.githubusercontent.com/90047999/161813083-207077e8-6ba6-4efa-9394-9f281f23562b.png) working. He gives the server IP and said 'access denied for ....' (server IP)

**Comment by N-fire** [comment]
https://github.com/overextended/oxmysql/issues/99
