### ISSUE TITLE
Error on QBCore 1.1.0 Sync Data "Players"

### ISSUE THREAD

**Issue by ToniSevHD** [overextended/oxmysql#107]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
It doesn't work well with QBCore 1.1.0, it doesn't sync well some character attributes like gender.

**Screenshots**
![image](https://user-images.githubusercontent.com/83134630/162875933-97530f44-08fb-4626-a782-35a8669d4be5.png)
![image](https://user-images.githubusercontent.com/83134630/162881438-bccd1af1-f6de-44c2-83cb-a652bf633149.png)

**Code**
```
[error oxmysql.txt](https://github.com/overextended/oxmysql/files/8469433/error.oxmysql.txt)

```

**Expected behavior**
Have no more errors.

**Additional context**
Nothing.

**Server details**
- TxAdmin FiveM by ZapHosting
- Cloud Gameserver
- QBCore 1.1.0

**Database details**
- MariaDB
- mysql-mariadb-20-104

**Comment by thelindat** [comment]
> Field 'gender' doesn't have a default value

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict

The prepare function was made transactional for large sets of data when using INSERT or UPDATE.

**Comment by thelindat** [comment]
Prepare was reverted, so this is resolved.
