### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bobiii94** [overextended/oxmysql#108]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ ] I am using the latest release

**Describe the bug**
hello, 
I encounter this problem except that no one can find a solution for me, the error is permanent but does not present any problem in the server, everything works perfectly

**Screenshots**
![Capture d’écran 2022-04-21 142737](https://user-images.githubusercontent.com/104144504/164459691-a9d411b8-ef00-4df8-a610-b3c461b889ac.png)

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**
I would like to know if the error comes from oxymsql or from the script

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by LukeWasTakenn** [comment]
Resource error, not related to oxmysql.
