### ISSUE TITLE
parameter 

### ISSUE THREAD

**Issue by GeekHamza1** [overextended/oxmysql#109]
hey ! 
i was using 
``exports.oxmysql:fetchSync('SELECT COUNT(*) as count FROM permission WHERE license = ?')``

its look like oxmysql exuciting the query even if the parameter license  not defined and also if the parameter is nill

so the script will continue work without errors and sending wrong result ..

**Comment by thelindat** [comment]
So don't send through the query without an argument. Lua nil will translate to NULL.

**Comment by GeekHamza1** [comment]
> So don't send through the query without an argument. Lua nil will translate to NULL.

if oxmysql did not print the error i will debug next lines instead of oxmysql line so this is bad idea

**Comment by thelindat** [comment]
> oxmysql did not print the error

Because it's a valid query, it counts the number of rows with NULL licenses, which is probably 0.

**Comment by GeekHamza1** [comment]
> > oxmysql did not print the error
> 
> Because it's a valid query, it counts the number of rows with NULL licenses, which is probably 0.

i know

but ,old  version of oxmysql was printing errors . undefined parameter

**Comment by thelindat** [comment]
How _old_ are you talking? Nil parameters have been handled for _months_.

**Comment by thelindat** [comment]
@GeekHamza1
![image](https://user-images.githubusercontent.com/65407488/165756955-9b77b1f0-d2b2-41fb-a858-01d027ceca1d.png)
Oh you poor fucking baby.

Having nil parameters handled as NULL as far better than dealing with INSERT and UPDATE queries breaking where NULL should be an accepted parameter, but instead needs to be an empty string.
