### ISSUE TITLE
Uncaught Error: Error in nested ref call.

### ISSUE THREAD

**Issue by erikmeyer08** [overextended/oxmysql#115]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [X ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I'm getting the exception shown below for multiple resources. The worst offender is the qb-garage script but I've seen other scripts have the issue too. 
I upgraded from oxmysql 1.9.2 to oxmysql 2.3.0 and that seems to be when this issue started.

**Screenshots**
![image](https://user-images.githubusercontent.com/43043270/168451372-fbeb9094-a604-4fb4-9ab3-5243699d4f1c.png)

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
Windows Server 2019 - FXServer
Ubuntu - SQL
FXServer 5562

**Database details**
- MariaDB 10

**Comment by thelindat** [comment]
Already fixed and pending a release. Note that the issue isn't _oxmysql_, it's the invoking resource.
An error occurred in the callback function.

**Comment by erikmeyer08** [comment]
Thanks!
