### ISSUE TITLE
keep getting nils

### ISSUE THREAD

**Issue by Mattt2283** [overextended/oxmysql#117]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
attempt to compare number with string
**Screenshots**
![image](https://user-images.githubusercontent.com/101035808/168706688-0f32db0b-81e5-473e-a091-714eee5fa103.png)

**Code**
```lua
EventHandler('esx:playerLoaded', function(playerId, xPlayer)
	Citizen.Wait(1000)
	local coords = xPlayer.getCoords(true)
	local distance = #(coords - Config.JailSpawnLocation)
	MySQL.Async.fetchAll('SELECT arrested_time FROM users WHERE identifier = @identifier', {
		['@identifier'] = xPlayer.identifier
	}, function(result)
		for _,v in pairs(result) do
			local info = json.decode(v.arrested_time)
			if info.prison > 0 then
				xPlayer.triggerEvent('esx_extendedjail:jailplayer', info.prison, { jail = 'prison', type = 'nofirst', distance = distance })
				PlayerArrested[playerId] = {TimeLeft = (info.prison * 60), identifier = xPlayer.getIdentifier(), realname = xPlayer.name, JailType = 'prison'}
				PlayersinJail = PlayersinJail + 1
			elseif info.pjail > 0 then
				xPlayer.triggerEvent('esx_extendedjail:jailplayer', info.pjail, { jail = 'pjail', type = 'nofirst', distance = distance })
				PlayerArrested[playerId] = {TimeLeft = (info.pjail * 60), identifier = xPlayer.getIdentifier(), realname = xPlayer.name, JailType = 'pjail'}
			end
		end
	end)
end)

```

**Expected behavior**

**Additional context**

someone else reported this on fourms: https://forum.cfx.re/t/standalone-oxmysql-lightweight-mysql-wrapper/4755120/298?
**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
“Omg oxmysql appears in the stack trace this is their fault”.

The error is from your code and it very clearly tells you the problem.
