### ISSUE TITLE
cant update 

### ISSUE THREAD

**Issue by LightUpFam** [overextended/oxmysql#131]
[      script:oxmysql] There is patch available for oxmysql - please update to the latest release (current version: 2.3.1)
[      script:oxmysql] https://github.com/overextended/oxmysql/releases/tag/v2.3.4

I tried every version above 2.3.1 and the resource wont load and causes all my other scripts to fail.  only solution was staying at 2.3.1

**Comment by thelindat** [comment]
> causes all my other scripts to fail

Amazingly descriptive.

Going to guess this is like the other 90% of people that download the source code instead of the very appropriately named 'oxmysql.zip'.

https://github.com/overextended/oxmysql/releases/download/v2.3.4/oxmysql.zip
