### ISSUE TITLE
Extend the oxmysql connection timeout

### ISSUE THREAD

**Issue by MvtiasG** [overextended/oxmysql#132]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ X] I am using the latest release
- [X ] I have referenced previously reported issues
- [ X] I have referenced available documentation and cannot resolve the issue
- [ X] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Does anyone know how I can stop this error when my server takes 1-5 seconds longer to start than normal ?
Does anyone know how to extend the connection time of oxmysql. I found this connection type for mysql "mysql://username:password@localhost/database?connectTimeout=3000000&acquireTimeout=3000000&waitForConnections=true&keepAlive=30&charset=utf8mb4" but for oxmysql I can't find anything. Could you help me ?

**Screenshots**
[https://cdn.discordapp.com/attachments/993941615636922540/993941636058980412/Screenshot_35.png](url)

**Comment by thelindat** [comment]
Start oversized assets (cars, mlos, etc) before resources.
