### ISSUE TITLE
oxmysql not starting

### ISSUE THREAD

**Issue by el3ctro4ndre** [overextended/oxmysql#133]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
The resource doesn't start

**Screenshots**
![image](https://user-images.githubusercontent.com/70718147/177503206-3539df4c-0931-4c0d-9c4f-f3bf7d8c24f8.png)

**Code**
-

**Expected behavior**
The plugin will starts.

**Additional context**
-

**Server details**
- FXServer artifact: 5704 (latest)
- Operating system: Windows 10 Pro

**Comment by thelindat** [comment]
Good thing you can download an actual release build instead of trying to let the yarn resource fuck up.
