### ISSUE TITLE
oxmysql error 

### ISSUE THREAD

**Issue by ohiostatedev** [overextended/oxmysql#134]
how do i fix this 
[      script:oxmysql] Error: Unable to establish a connection to the database!
[      script:oxmysql] [Error: connect ETIMEDOUT]

**Comment by NRTnarathip** [comment]
you setup server config incorrect

**Comment by darksaid98** [comment]
As was stated above. Read and follow the documentation [here](https://overextended.github.io/docs/oxmysql).

**Comment by mrsmit00001** [comment]
[      script:oxmysql] Error: ethicalpixel-adminmenu was unable to execute a query!
[      script:oxmysql] Query: SELECT * FROM ethicalpixel_admin_banned WHERE license = ?
[      script:oxmysql] ["license:3dc6f42f0d75e4b8104486b5cdb3fc997abb418e"]
[      script:oxmysql] Table 'qbcoreframework_5881c7.ethicalpixel_admin_banned' doesn't exist
