### ISSUE TITLE
Better documentation on update process for oxmysql package

### ISSUE THREAD

**Issue by Wildeman13** [overextended/oxmysql#137]
**Is your feature request related to a problem? Please describe.**
I am attempting to update oxmysql-2.3.4 to the latest oxmysql-2.4.0 and cannot find any documentation on how to do this without apparently failing to maintain any of my existing setup. When I git pull the latest version, 2.4.0, and attempt to FTP this to my server, at server startup oxmysql seems to fail to start and all qb-core mods related to oxmysql also fail to start. Yarn also throws out multiple errors during the startup process as it appears to be trying to rebuild oxmysql. 

**Describe the solution you'd like**
I would like a step by step process on what files to save/edit to carry over from previous version to latest version. Or a script that can be run to create a changes file in order to allow for a git pull of the latest update and a push of those files over to the server maintaining existing settings and configs. 

**Describe alternatives you've considered**
I am currently attempting to do a file by file comparison of my working oxmysql-2.3.4  installation versus what's been pulled from the git repo latest, currently 2.4.0. 

**Additional context**
I am not sure what else to provide. I have attempted to use internet search to find this answered anywhere else, and have found nothing. I am either completely doing this wrong (Highly suspect this is the case) or else I a am simply missing the list of files containing the configs I need to ensure are in place in the new version, 2.4.0.

**Comment by thelindat** [comment]
I’m confused about why you’re using git pull and then uploading the source code to your server.

You don’t even need to worry about manually building oxmysql; just download the _already built_ release, and save yourself the trouble.

If you do want to put in the effort of building don’t rely on the trash yarn shit resource.

**Comment by Wildeman13** [comment]
As I said initially... I was missing something. That was the ZIP file being the already built resource. Thank you, that was the problem, in that I was trying to use the source files versus the built package. Thanks!
