### ISSUE TITLE
Having an error with esx_datastore and oxmysql

### ISSUE THREAD

**Issue by WiteWxlf** [overextended/oxmysql#139]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x ] I am using the latest release
- [ x ] I have referenced previously reported issues
- [ x ] I have referenced available documentation and cannot resolve the issue
- [ x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
When I launch my Server im getting this Error:
[script:oxmysql] Database server connection established!
[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/main.lua:18: table index is nil
[script:esx_datastore] > handler (@esx_datastore/server/main.lua:18)
[script:esx_datastore] > <unknown> (@oxmysql/dist/build.js:21729)
[script:esx_datastore] > process TicksAndRejections (node:internal/process/task_queues:96)
[script:esx_datastore] > async rawQuery (@oxmysql/dist/build.js:21719)

I tried reinstalling both, the sql and oxmysql but nothing of that worked. 
Im really new in these things here so excuse me not knowing that much :)

**Screenshots**
![image](https://user-images.githubusercontent.com/110856150/183509925-5e38a537-8089-45d2-b942-ca508f141de8.png)

**Comment by thelindat** [comment]
> [ x ] I'm certain this is an issue with oxymysql, and not with my resource

sure

**Comment by thelindat** [comment]
> [script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/main.lua:18: table index is nil

**Comment by WiteWxlf** [comment]
Could you please describe it a bit more for me, I don't really get what you want to say.

**Comment by thelindat** [comment]
> SCRIPT ERROR
> esx_datastore
> server/main.lua:18
> table index is nil

**Comment by WiteWxlf** [comment]
> > SCRIPT ERROR
> 
> > esx_datastore
> 
> > server/main.lua:18
> 
> > table index is nil

So you are telling me that I need to search in the esx_datastore file for the error? Please just answer "yes" or "no".

**Comment by LukeWasTakenn** [comment]
yes
