### ISSUE TITLE
V1.2.0 specific problem

### ISSUE THREAD

**Issue by BerkieBb** [overextended/oxmysql#14]
It's not getting a specific column's value on the newest release
Error:![Naamloos](https://user-images.githubusercontent.com/82737367/133003745-7a1c1f49-87d9-4839-9df5-a5db49312a63.png)
Query:

```lua
exports.oxmysql:insert('INSERT INTO players (citizenid, cid, license, name, money, charinfo, job, gang, position, metadata) VALUES (@citizenid, @cid, @license, @name, @money, @charinfo, @job, @gang, @position, @metadata)', {
  ['@citizenid'] = PlayerData.citizenid,
  ['@cid'] = tonumber(PlayerData.cid),
  ['@license'] = PlayerData.license,
  ['@name'] = PlayerData.name,
  ['@money'] = json.encode(PlayerData.money),
  ['@charinfo'] = json.encode(PlayerData.charinfo),
  ['@job'] = json.encode(PlayerData.job),
  ['@gang'] = json.encode(PlayerData.gang),
  ['@position'] = json.encode(PlayerData.position),
  ['@metadata'] = json.encode(PlayerData.metadata)
})
```

**Comment by dunak-debug** [comment]
```lua
exports.oxmysql:insert('INSERT INTO players (citizenid, cid, license, name, money, charinfo, job, gang, position, metadata) VALUES (?)', {{
  PlayerData.citizenid,
  tonumber(PlayerData.cid),
  PlayerData.license,
  PlayerData.name,
  json.encode(PlayerData.money),
  json.encode(PlayerData.charinfo),
  json.encode(PlayerData.job),
  json.encode(PlayerData.gang),
  json.encode(PlayerData.position),
  json.encode(PlayerData.metadata)
}})
```

Can you try this please?

**Comment by BerkieBb** [comment]
That seemed to have fixed it, thanks!

**Comment by BerkieBb** [comment]
Is there any way I can keep the original query or is this all I can do?

**Comment by dunak-debug** [comment]
Backward compatibility with ghmatti/mysql-async `(@params)` is very experimental and I suggest to not use that. It will became deprecated in future anyway because `?` or `:` are built-in functionality of `node-mysql2` package and they are stable.

**Option 1 - unnamed parameters:**


> ```lua
> exports.oxmysql:insert('INSERT INTO players (citizenid, cid, license, name, money, charinfo, job, gang, position, metadata) VALUES (?)', {{
>   PlayerData.citizenid,
>   tonumber(PlayerData.cid),
>   PlayerData.license,
>   PlayerData.name,
>   json.encode(PlayerData.money),
>   json.encode(PlayerData.charinfo),
>   json.encode(PlayerData.job),
>   json.encode(PlayerData.gang),
>   json.encode(PlayerData.position),
>   json.encode(PlayerData.metadata)
> }})
> ```
> 
> Can you try this please?

**Option 2 - named parameters**

```lua
exports.oxmysql:insert('INSERT INTO players (citizenid, cid, license, name, money, charinfo, job, gang, position, metadata) VALUES (:citizenid, :cid, :license, :name, :money, :charinfo, :job, :gang, :position, :metadata)', {
  citizenid = PlayerData.citizenid,
  cid = tonumber(PlayerData.cid),
  license = PlayerData.license,
  name = PlayerData.name,
  money = json.encode(PlayerData.money),
  -- or with brackets 
  ['charinfo'] = json.encode(PlayerData.charinfo),
  ['job'] = json.encode(PlayerData.job),
  ['gang'] = json.encode(PlayerData.gang),
  ['position'] = json.encode(PlayerData.position),
  ['metadata'] = json.encode(PlayerData.metadata)
})
```

In my opinion the first one option is also shorter ;)

**Comment by dunak-debug** [comment]
> That seemed to have fixed it, thanks!

Anyway I will look onto fixing @ syntax. I may forget something in https://github.com/overextended/oxmysql/blob/v1.2.0/patches/named-placeholders%2B1.1.2.patch

**Comment by BerkieBb** [comment]
Alright, thanks, I hope you fix the @ syntax as it is otherwise loads of stuff that need to be changed and I don't really want that yet

**Comment by GhzGarage** [comment]
Just a heads up, re-did all queries for qb-core and all is working well with 1.2 now. The only issue we ran into was when defining values, you CANNOT use (?) by itself. 

Example:

('INSERT INTO houselocations (name, label, coords, owned, price, tier) VALUES (?)' <- does NOT work

('INSERT INTO houselocations (name, label, coords, owned, price, tier) VALUES (?, ?, ?, ?, ?, ?)' <- DOES work

**Comment by dunak-debug** [comment]
You can run (?) but you have to wrap parameters as nested table.

> ```lua
> ```lua
> exports.oxmysql:insert('INSERT INTO players (citizenid, cid, license, name, money, charinfo, job, gang, position, metadata) VALUES (?)', {{
>   PlayerData.citizenid,
>   tonumber(PlayerData.cid),
>   PlayerData.license,
>   PlayerData.name,
>   json.encode(PlayerData.money),
>   json.encode(PlayerData.charinfo),
>   json.encode(PlayerData.job),
>   json.encode(PlayerData.gang),
>   json.encode(PlayerData.position),
>   json.encode(PlayerData.metadata)
> }})
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Can you try this please?
> ```
