### ISSUE TITLE
Debug mode for specific resources

### ISSUE THREAD

**Issue by awojnarek** [overextended/oxmysql#140]
# Problem Statement 
Since escrow has exploded and changed FiveM, there has been a new problem that has been created in the community: troubleshooting escrowed resources.

Many times, when working with a developer of an escrowed resource, they may ask you to turn on MySQL debug mode. 

This is problematic because to turn on Debug mode for an entire server is going to messy, chatty and noisy.

# Possible Solution
If you could turn on debug for specific resources, this would vastly help enable proper troubleshooting. So being able to turn on debug mode for specific resources and log only oxmysql queries from those resources would be a massive boon to the community.

Thanks.

**Comment by thelindat** [comment]
I'll set it up later.

**Comment by awojnarek** [comment]
Excellent. Thank you sir.

**Comment by thelindat** [comment]
```
set mysql_debug [
    "ox_core",
    "ox_inventory"
]
```
Would output resources from the given entries to the console, otherwise only report slow queries.
I'll add a command to add or remove resources to the array later, and commands for other values as well to remove the need to restart to change settings.
