### ISSUE TITLE
nil value on a query, what happen?

### ISSUE THREAD

**Issue by Kurosak1ll** [overextended/oxmysql#141]
Hi and good night right here!

i have a simple issue with this, im get a nil value on this query:

![image](https://user-images.githubusercontent.com/99582773/185774091-e651c53b-c097-40e1-bc0b-91cd7c876498.png)

the issue is when i try to get the value of  "if tonumber(query_users[1].fragile) >= tonumber(query[1].fragile) then" gets a nil value.

✅I have the lastest release.
✅I have the lastest artifacts.
✅This working fine on mysql-async, im change to this one for this security and using mariadb right now.

I mean that's a issue on the query, im tried everything and this is my last attemp after remove this script.

Hope you hel me a lot.

![image](https://user-images.githubusercontent.com/99582773/185774400-00fa3de6-3975-46c9-84bf-52fd1ed4eaad.png)

**Comment by darksaid98** [comment]
Umm, `tonumber(query_users[1].fragile)` or `tonumber(query[1].fragile)` is nil. And you cannot compare a number to `nil`.

GitHub should be used for bug reports and feature requests etc.

**Helping people learn how to use SQL queries or Lua falls outside what GitHub issues are for.**

**Comment by Kurosak1ll** [comment]
Ok, understand, the second query is the issue, casue it read only the first column, thats why asking about a issue on this. Im read all about, but if this one recognize the mysql async querys, this issue is really weird.
