### ISSUE TITLE
No such export query in resource oxmysql On Debian, but not Windows

### ISSUE THREAD

**Issue by fab5741** [overextended/oxmysql#146]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I use OxMysql to get access to DB. It works perfectly fine on Windows server (my local dev environement). But on Distant server (Linux), it don't works as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/7713254/190258588-9add2e53-39fa-44b0-8ba7-9ecc4148d172.png)

**Code**
	'@oxmysql/lib/MySQL.lua',

**Expected behavior**
Should import Mysql functions

**Server details**
Linux

**Database details**
Mysql 5.7

**Comment by thelindat** [comment]
Not a bug. Fix your load order, or use the _built release_.

**Comment by fab5741** [comment]
OxMysql is already, the first Script i load, and i am using the Relase version

and it works perfectly fine on windows... but not Debian

**Comment by thelindat** [comment]
You issue, not the resource. You think we don't use linux?
