### ISSUE TITLE
Bug after update to 2.5.1

### ISSUE THREAD

**Issue by MedusaRP** [overextended/oxmysql#147]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [ x] I have referenced previously reported issues
- [ x] I have referenced available documentation and cannot resolve the issue
- [ x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
The bug appeared after update to the latest version 2.5.1

**Error on console**
```lua
[      script:oxmysql] Uncaught TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (123)
[      script:oxmysql] node:internal/errors(464,5): __node_internal_captureLargerStackTrace
[      script:oxmysql] node:internal/errors(371,5): NodeError
[      script:oxmysql] node:internal/crypto/hash(105,11): update
[      script:oxmysql] @oxmysql/dist/build.js(8985,12): sha1
[      script:oxmysql] @oxmysql/dist/build.js(9012,22): token
[      script:oxmysql] @oxmysql/dist/build.js(9865,30): HandshakeResponse
[      script:oxmysql] @oxmysql/dist/build.js(11069,35): sendCredentials
[      script:oxmysql] @oxmysql/dist/build.js(11141,16): handshakeInit
[      script:oxmysql] @oxmysql/dist/build.js(10526,26): execute
[      script:oxmysql] @oxmysql/dist/build.js(14232,36): handlePacket
[      script:oxmysql] 
[      script:oxmysql] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (123)

.
.
.

[      script:oxmysql] Error: Unable to establish a connection to the database!
[      script:oxmysql] [Error: read ECONNRESET]
```

**Server details**
- FXServer artifact - 5975
- GameBuild - 2699
- Operating system - Windows 10 Home

**Database details**
The error appeared with XAMPP and with MariaDB 10.11

**Comment by thelindat** [comment]
What's your connection string (censor sensitive information)?

**Comment by darksaid98** [comment]
I can reproduce this on a dev DB if the password is a valid `number`. Changing it to `123four` resolves the issue.

```
## These give the TS type error
set mysql_connection_string "mysql://dark1:123@127.0.0.1/foyoum?charset=utf8mb4"
set mysql_connection_string "user=dark1;password=123;host=127.0.0.1;port=3306;database=foyoum;charset=utf8mb4"

## These work fine
set mysql_connection_string "mysql://dark2:12three@127.0.0.1/foyoum?charset=utf8mb4"
set mysql_connection_string "user=dark2;password=12three;host=127.0.0.1;port=3306;database=foyoum;charset=utf8mb4"
```

Leads me to believe that the password arg is wrongly interpreted as a number (when valid) instead of a string somewhere. Casting it to a string would probably be a quick but dirty fix. It would also explain why this issue hasn't been reported until now since most people don't use `123` or such as password.

Can confirm regression appeared first in **v2.5.1**. A wild guess is some typing wrongly changed in https://github.com/overextended/oxmysql/commit/8fe63bc88ad9652dc2bf26b06016b1eea1baff42 perhaps?
