### ISSUE TITLE
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: Query expected a string but received object instead

### ISSUE THREAD

**Issue by Loyzahk** [overextended/oxmysql#148]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x ] I am using the latest release
- [ x ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [ x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I am making a fivem server and this oxmysql error is thrown on the console all the time, I have tried to update it, change the qb-core to the most recent one, but I cannot find a way to solve the problem

**Screenshots**
![image](https://user-images.githubusercontent.com/95712901/199624359-d5a2966b-1003-487a-a9d1-401190ce62ea.png)

**Code**
```bat
   [      script:oxmysql] Database server connection established!
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: xxxxxxxxxxxxxxxxx
[     script:dpemotes] 
[     script:dpemotes] dp Emotes (dpemotes) is up to date. (173)
[ script:connectqueue] QUEUE: C i g a r x t t e[license:xxxxxxxxxxxxxxx] was placed 1/1 in queue
[ script:connectqueue] QUEUE: C i g a r x t t e[license:xxxxxxxxxxxxxxxxxx] is loading into the server
[ citizen-server-impl] Server list query returned an error: System.Net.Sockets.SocketException: Connection refused <- System.Net.Http.HttpRequestException: Connection refused (xxxxxxxxxxxxx)
[      script:qb-core] [qb-core:LOG] C i g a r x t t e PLAYER SAVED!
[script:qb-multichara] [qb-core] C i g a r x t t e (Citizen ID: xxxxxxxxxxx) has succesfully loaded!
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: Query expected a string but received object instead
[      script:oxmysql] > parseArguments (@oxmysql/dist/build.js:22049)
[      script:oxmysql] > rawQuery (@oxmysql/dist/build.js:22222)
[      script:oxmysql] 
[script:qb-vehiclesho] SCRIPT ERROR: @qb-vehicleshop/server.lua:433: qb-vehicleshop was unable to execute a query!
[script:qb-vehiclesho] Unknown column 'balance' in 'where clause'
[script:qb-vehiclesho] SELECT * FROM player_vehicles WHERE citizenid = ? AND balance > 0 AND financetime < 1 ["xxxxxxxxxx"]
[script:qb-vehiclesho] > handler (@qb-vehicleshop/server.lua:433)
[script:qb-vehiclesho] > <unknown> (@oxmysql/dist/build.js:22255)
[script:qb-vehiclesho] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:qb-vehiclesho] > async rawQuery (@oxmysql/dist/build.js:22223)
[      script:qb-core] [qb-core:LOG] C i g a r x t t e PLAYER SAVED!
```

**Server details**

- W11 and W10 have the same problem

**Database details**
- MariaDB / MySQL

**Comment by thelindat** [comment]
Neither of these are issues with oxmysql.

> Query expected a string but received object instead

Instead of a query like 'SELECT row FROM table WHERE column = ?', you're sending a table as the first argument.

> Unknown column 'balance' in 'where clause'

Yes, that is what happens when you query using a column that doesn't exist..

**Comment by Loyzahk** [comment]
But I could remove vehicleshop and the error will continue to appear, that's what I don't understand why it appears, because qb-vehicleshop is the original of qbcore and I just installed it
