### ISSUE TITLE
Why delete my issue if its not solved.?

### ISSUE THREAD

**Issue by Loyzahk** [overextended/oxmysql#149]
I quited qb-vehicleshop, and i have the same error of oxmysql
![image](https://user-images.githubusercontent.com/95712901/199626120-61cfe4af-3bf6-47bd-ab66-973939afe9a5.png)
Console: 
 [      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: Query expected a string but received object instead
[      script:oxmysql] > parseArguments (@oxmysql/dist/build.js:22049)
[      script:oxmysql] > rawQuery (@oxmysql/dist/build.js:22222)
[      script:oxmysql]

**Comment by thelindat** [comment]
What don't you understand? This isn't support for random scripts sending incorrect parameters to oxmysql.
