### ISSUE TITLE
I could delete the entire server, maybe that's the only way your oxmysql shit would work

### ISSUE THREAD

**Issue by Loyzahk** [overextended/oxmysql#150]
I could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would workI could delete the entire server, maybe that's the only way your oxmysql shit would work

**Comment by DokaDoka** [comment]
please do
