### ISSUE TITLE
My Server Stopped Working after Updating 

### ISSUE THREAD

**Issue by Gamezff** [overextended/oxmysql#151]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I have no clue but my server is not working because of it.
*
![Screenshot 2022-11-02 191235](https://user-images.githubusercontent.com/113258941/199671528-57ccedd1-79f4-4b6c-aa3e-77f579da325b.png)
*Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by LukeWasTakenn** [comment]
Download the release build not source code.
