### ISSUE TITLE
Im using the newest update...

### ISSUE THREAD

**Issue by xxUnknown13xx** [overextended/oxmysql#152]
IDK why i get this error. I get it when I take a picture using twitter. I did not get this error before.

![oxmysqll](https://user-images.githubusercontent.com/113321753/199911203-ae93b395-10ba-4a9a-a0a2-50e79fb9618f.PNG)

**Comment by thelindat** [comment]
You're sending an invalid date format for the "date" field (takes datetime). Take it up with the author.
