### ISSUE TITLE
Export error after new update

### ISSUE THREAD

**Issue by Dejvi1** [overextended/oxmysql#153]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

Ive updated to a new version of the oxmysql and now im getting multiple errors for scripts like esx_multichar etc..
oxmysql/lib/MySQL.lua:94: No such export query in resource oxmysql

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**
No error 

**Additional context**
In previous version there was no problem with that

**Server details**
- FXServer artifact ->latest recommended
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
Every update there's always some absolute tool who has to post the _exact same garbage_ because they don't know how to download a release.

Is it really _so_ difficult?

https://github.com/overextended/oxmysql/releases/download/v2.5.3/oxmysql.zip
