### ISSUE TITLE
Script Error (Unhandled Rejction)

### ISSUE THREAD

**Issue by KSJDiamondGaming** [overextended/oxmysql#157]
This same Error was posted 15days ago, and reported as not a fault by oxmysql, which i understand. Ive read the reports, but it was closed with no understanding to my self on how to resolve it and this is the closest point ive come to finding a solution, Hoping for more help. Please

**Comment by KSJDiamondGaming** [comment]
![AAA](https://user-images.githubusercontent.com/83096833/202488161-d12ce85d-5807-4879-b4a5-6c77c565cc45.png)

**Comment by thelindat** [comment]
You can either
- search for a resource that is using `exports.oxmysql.`, which should be  `exports.oxmysql:` (well, _should_ be using MySQL/lib.lua)
- fix fxserver so stack traces don't vanish when using promises

**Comment by ALTITUDE-DEV-FR** [comment]
Thanks for the Fix <3 
Owner of https://undeadcore.com/ use oxymysql <3
