### ISSUE TITLE
 @bb-trucker/server.lua:242: attempt to compare nil with number

### ISSUE THREAD

**Issue by Maxhero54** [overextended/oxmysql#158]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ x] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
sorry my english not well..
my issued  script  truck_logistic
i didint have  truck keys  (i mean when spawned truck all doors locked i didint open ) 
 and   below Error when i try chose  use  normal transport  jobs (mean not need own any truck)

plus addon Trucks  same 

**Screenshots**
@bb-trucker/server.lua:242 below 
https://prnt.sc/Ie2X3CNy956A

**Code**
Error on console below
[   script:bb-trucker] SCRIPT ERROR: @bb-trucker/server.lua:242: attempt to compare nil with number
[   script:bb-trucker] > ref (@bb-trucker/server.lua:242)
[   script:bb-trucker] > <unknown> (@oxmysql/dist/build.js:22252)
[   script:bb-trucker] > processTicksAndRejections (node:internal/process/task_queues:96)

**Expected behavior**

**Additional context**

**Server details**
QBcore  
v5.0.1 atop FXServer 6117
 Windows 10

**Database details**
- MariaDB 10.4 27

thanks

**Comment by thelindat** [comment]
> attempt to compare nil with number

Does that sound like a _MySQL_ error?

> SCRIPT ERROR: @bb-trucker/server.lua:242

That's the source of the problem.

**Comment by Maxhero54** [comment]
Thanks for  swift replay 
do you have idea how can i solve  it ?

script SS
https://prnt.sc/Ie2X3CNy956A
