### ISSUE TITLE
CONCAT Doesnt work

### ISSUE THREAD

**Issue by Kinoki1** [overextended/oxmysql#16]
Hello, i found problem with CONCAT in oxmysql, here is example:

`	local resultDepartment = exports.oxmysql:fetch('SELECT CONCAT(\'(\',job.label,\' - \', grade.label,\')\') as departmentGrade FROM `jobs` job join `job_grades` grade on job.name = grade.job_name WHERE job.name=@job and grade.grade = @job_grade', {
		['job'] = jobName,
		['job_grade'] = jobGrade
	} );`

and error:

`[      script:oxmysql] Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?.label,' - ', grade.label,')') as departmentGrade FROM jobs job join job_gra' at line 1 SELECT CONCAT('(',job.label,' - ', grade.label,')') as departmentGrade FROM jobs job join job_grades` grade on job.name = grade.job_name WHERE job.name=:job and grade.grade = :job_grade {
[      script:oxmysql]   "job_grade": 3,
[      script:oxmysql]   "job": "sheriff"`

**Comment by dunak-debug** [comment]
Try 1.3.0

**Comment by BaziForYou** [comment]
> Try 1.3.0
![image](https://user-images.githubusercontent.com/20565441/133936757-8d6480c3-c2bc-411a-82e0-86f899525b53.png)
but work on mysql-async i dont have any idea :|

[      script:oxmysql] [DEBUG] MDC took 15.9089ms to execute a query!
[      script:oxmysql]         SELECT * FROM users WHERE identifier = @identifier {"identifier":"2:110000115bcaf6d"}
[      script:oxmysql] [ERROR] MDC was unable to execute a query!
[      script:oxmysql]         You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.label,' - ', grade.label,')') as departmentGrade FROM `jobs` job join `job_g...' at line 1
[      script:oxmysql]         SELECT CONCAT('(''police'.label,' - ', grade.label,')') as departmentGrade FROM `jobs` job join `job_grades` grade on job.name = grade.job_name WHERE job.name='police' and grade.grade = 5
[      script:oxmysql] Trace: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.label,' - ', grade.label,')') as departmentGrade FROM `jobs` job join `job_g...' at line 1
[      script:oxmysql]     at PromisePool.query (@oxmysql/oxmysql.js:17241:22)
[      script:oxmysql]     at execute (@oxmysql/oxmysql.js:19766:68)
[      script:oxmysql]     at Object.callback (@oxmysql/oxmysql.js:20228:52)
[      script:oxmysql]     at citizen:/scripting/v8/main.js:135:43
[      script:oxmysql]     at Number.__cfx_wrap_954 (citizen:/scripting/v8/main.js:24:12)
[      script:oxmysql]     at citizen:/scripting/v8/main.js:30:16
[      script:oxmysql]     at citizen:/scripting/v8/main.js:134:11
[      script:oxmysql]     at citizen:/scripting/v8/main.js:83:28
[      script:oxmysql]     at Number.__cfx_wrap_953 (citizen:/scripting/v8/main.js:24:12)
[      script:oxmysql]     at citizen:/scripting/v8/main.js:30:16
[      script:oxmysql]     at Console.trace (citizen:/scripting/v8/console.js:297:19)
[      script:oxmysql]     at execute (@oxmysql/oxmysql.js:19783:59)

**Comment by thelindat** [comment]
```lua
exports.oxmysql:scalar("SELECT CONCAT('(',job.label,' - ', grade.label,')') as departmentGrade FROM jobs job join job_grades grade on job.name = grade.job_name WHERE job.name=? and grade.grade = ?", { jobName, jobGrade }, function(result)
	print(result)
end)
```
