### ISSUE TITLE
Can't connect to database are moving to VPS

### ISSUE THREAD

**Issue by nwvh** [overextended/oxmysql#160]
Hey, I've moved my server that I've been hosting locally the whole time to a Debian VPS, moved the server folder here, started it but it's throwing an error:

```
[      script:oxmysql] Error: Unable to establish a connection to the database!
[      script:oxmysql] [Error: Access denied for user 'root'@'localhost']
```

How can I make it connect to the db? Thanks

**Comment by darksaid98** [comment]
Read documentation https://overextended.github.io/docs/oxmysql/#configuration.
