### ISSUE TITLE
Slow query warnings

### ISSUE THREAD

**Issue by BrazyDeveloper** [overextended/oxmysql#165]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/123915220/215698976-f2ab1757-fb91-4ba5-951a-b351d7bbcbda.png)

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
Wow. Amazing quality "bug" report, thank you for this rare opportunity! The way you described this "bug" makes my heart skip a beat.

---

You're executing _God knows_ how many queries during the first server tick and there's a lot of other things happening like loading resources and terrible Lua-based anticheats which leads to a server thread hitch (as it states, right there). The query warnings aren't really query time but query _response_ time, which is affected by server hitches.

What are you even complaining about or asking for here? Such a stupid waste of time.

**Comment by BrazyDeveloper** [comment]
Shut the fuck up you fucking little wanker. Look at you, you fat neek.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by thelindat** [comment]
> Shut the fuck up you fucking little wanker. Look at you, you fat neek.

You add a stupid screenshot to the issue template and call it a day, incapable of even doing the bare minimum when trying to report what you believe to be an issue. How about you use your brain, you incompetent child?
