### ISSUE TITLE
Debug Print

### ISSUE THREAD

**Issue by AlbatracZ** [overextended/oxmysql#166]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
How can i disable showing a debug prints

**Comment by AlbatracZ** [comment]
![image](https://user-images.githubusercontent.com/20631193/218289488-efc35bc1-af35-4ead-be98-a340a98e07f9.png)

**Comment by darksaid98** [comment]
This is not a bug. Read the documentation: https://overextended.github.io/docs/oxmysql/#configuration.

**Comment by AlbatracZ** [comment]
im already tried this documentation.
