### ISSUE TITLE
Question replacement license to steamID

### ISSUE THREAD

**Issue by Zilockegaming** [overextended/oxmysql#167]
its a question not an issue or request

Can i replace the license to steam ID so everyone can connect with the main character i have an issue that when im on my laptop i need to create an new character and its the same steam ID

**Comment by thelindat** [comment]
This has _what_ to do with oxmysql?

**Comment by Zilockegaming** [comment]
well i saw in my sql server that its regesting rockstar lisence but i tought mabey if i can chainge the lisence to steam id with ocmysql that it is fixed

**Comment by thelindat** [comment]
That isn't what oxmysql does; it doesn't even come with a database let alone tables and random nonsense. Go look at whatever framework your using.

Also, just don't use steam - it's garbage and problematic. https://forum.cfx.re/t/a-psa-on-steam-identifier-support/517277

You should be using license2.
