### ISSUE TITLE
Result type does not have length.

### ISSUE THREAD

**Issue by tomasalves8** [overextended/oxmysql#169]
## Issue checklist

- [X] I am using the latest release
- [X] I have referenced previously reported issues
- [X] I have referenced available documentation and cannot resolve the issue
- [X] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

When using typescript the editor shows that the `Result` type doesn't have length and can't by accessed by index.
The code works fine, it's just a type error.

**Screenshots**

![](https://i.imgur.com/cLTBFpM.png)
![](https://i.imgur.com/HrADeK7.png)

**Code**
```ts
	const result = await oxmysql.query('SELECT CONCAT(JSON_EXTRACT(charinfo, "$.firstname"), " ", JSON_EXTRACT(charinfo, "$.lastname")) AS name from players where id = ?', [charID]);
    	if (result == null || result.length == 0) {
		return null;
	}else {
		let player = result[0];
		return player;
	}
```

**Expected behavior**
Should not show any errors

**Additional context**

**Server details**
- FXServer artifact: Not relevant
- Operating system:  Not relevant

**Database details**
- MariaDB or MySQL: MariaDB 
- Version: 10.4.24

**Comment by LukeWasTakenn** [comment]
Use generics to type cast the result.
