### ISSUE TITLE
error ox lib & ox inventory dont lunch

### ISSUE THREAD

**Issue by brucewaynetv** [overextended/oxmysql#170]
my server return this error after installing oxmysql

[ citizen-server-impl] Build tasks completed - starting resource oxmysql.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. server needs to be 5848 or higher
[    c-resources-core] Could not start dependency ox_lib for resource ox_inventory.
[    c-resources-core] Resource 'ox_inventory' can't run:
[    c-resources-core]   1. server needs to be 5848 or higher
[ citizen-server-impl] Started resource oxmysql
[1/4] Resolving packages...
success Already up-to-date.
Done in 40.45s.
[ citizen-server-impl] Build tasks completed - starting resource oxmysql.

**Comment by jag3dagster** [comment]
Answer is provided for you in the block that you posted.

`1. server needs to be 5848 or higher`

**Comment by brucewaynetv** [comment]
what is 5848?

**Comment by jag3dagster** [comment]
The FXServer version
https://docs.fivem.net/docs/server-manual/setting-up-a-server/

**Comment by brucewaynetv** [comment]
yes thank you i was just thinking about that
