### ISSUE TITLE
yarn install fails when starting oxmysql on fxserver

### ISSUE THREAD

**Issue by thelindat** [overextended/oxmysql#174]
## oxmysql does not use yarn
The yarn resource for fxserver aggressively tries to install and build _any and all_ resources with a package.json file in the root directory. package.json only exists when you download the _source code_ for oxmysql.

Download an actual release which has been built and is capable of being loaded and run by FXServer.
  - https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip

**Comment by thelindat** [comment]
Average fivem user, just in case you're wondering why we hate working on this project.
![image](https://user-images.githubusercontent.com/65407488/229254815-d22753c2-f3f2-4af9-a53c-1f7577f36b1d.png)

**Comment by m0rtl0ck** [comment]
I had this same issue.  however, if you get the latest version (not the main one that automatically comes up) it comes pre built so yarn won't try and build it and break it.
