### ISSUE TITLE
any idea?

### ISSUE THREAD

**Issue by SubZon3** [overextended/oxmysql#175]
[      script:oxmysql] SCRIPT ERROR in promise (unhandled rejection): Error: esx_license was unable to execute a query!
[      script:oxmysql] Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
[      script:oxmysql] SELECT user_licenses.type, licenses.label FROM user_licenses LEFT JOIN licenses ON user_licenses.type = licenses.type WHERE owner = ? ["char1:0e765dff374e06aa9d05a8ae9772014e3ca44b8d"]

**Comment by thelindat** [comment]
It tells you the issue, and it's _nothing to do with oxmysql even_.

> [ script:oxmysql] Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
[ script:oxmysql] SELECT user_licenses.type, licenses.label FROM user_licenses LEFT JOIN licenses ON user_licenses.type = licenses.type WHERE owner = ? ["char1:0e765dff374e06aa9d05a8ae9772014e3ca44b8d"]
