### ISSUE TITLE
"No such export * in resource oxmysql"

### ISSUE THREAD

**Issue by Gixxy211** [overextended/oxmysql#176]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
"No such export * in resource oxmysql" when updating to new release 

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by LukeWasTakenn** [comment]
https://github.com/overextended/oxmysql/issues/154
