### ISSUE TITLE
Don't know what's going on..?

### ISSUE THREAD

**Issue by Dmooooo** [overextended/oxmysql#177]
I'm using the latest oxmysql and I had to reinstall my server and I downloaded the updated oxmysql and changed the set mysql_connection_string "user=root;password=12345;host=localhost;port=3306;database=es_extended;charset=utf8mb4" in the server cfg and I added set mysql_slow_query_warning 150 set mysql_debug true into the server cfg as well now I'm running into these errors? 
![image](https://github.com/overextended/oxmysql/assets/133716279/53a6d49e-7cfb-4dff-af03-4f5c007a5c18)
![image](https://github.com/overextended/oxmysql/assets/133716279/b04574ef-1979-49d6-a318-f50f72701e70)

**Comment by thelindat** [comment]
> I'm using [...] set mysql_debug true
