### ISSUE TITLE
An option to force prepare to always return a table of rows; do not unpack single rows into key/value pairs

### ISSUE THREAD

**Issue by lewisclark** [overextended/oxmysql#179]
I find it inconsistent that the returned rows of `prepare` can change depending on whether a single row or many rows were returned. I understand that there is a choice when not using prepared queries (e.g. query() vs single()), so it only seems fitting that it be the case for prepared queries, too. 

It would be nice to have the option of forcing it to return a table of rows, regardless of the number of rows returned. 

Example:
```lua
local rows = db:SelectItemsByCharacterId(character:GetId())
for _, row in pairs(rows) do
    local itemspec = ItemSpec.New(
        row.itemspec_id,
        row.name,
        row.enum,
        row.max_quantity,
        row.weight
    )
end
```

This code suddenly breaks when the player has only one stored item, as `rows` is now unpacked into key/value pairs where keys are column names.

```
{
  {
    column1 = value,
    column2 = value,
    ...
  },
  {
    column1 = value,
    column2 = value,
    ...
  }
  ...
}
```

Becomes

```
{
  column1 = value,
  column2 = value,
  ...
}
```

**Comment by thelindat** [comment]
Didn't do much testing with https://github.com/overextended/oxmysql/commit/e8f1abcab7d0f962dec717375395b8edfa09747a but try building it and see how it goes.

```lua
local rows = MySQL.rawExecute.await(query, parameters)

if rows then
    for _, row in pairs(rows) do
        ....
    end
end
```

**Comment by lewisclark** [comment]
> Didn't do much testing with [e8f1abc](https://github.com/overextended/oxmysql/commit/e8f1abcab7d0f962dec717375395b8edfa09747a) but try building it and see how it goes.
> 
> ```lua
> local rows = MySQL.rawExecute.await(query, parameters)
> 
> if rows then
>     for _, row in pairs(rows) do
>         ....
>     end
> end
> ```

I've built it and tried it out, it seems to be working great. Cheers!

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/releases/tag/v2.7.0
