### ISSUE TITLE
Specific SELECT is not working!

### ISSUE THREAD

**Issue by nyoakaway** [overextended/oxmysql#18]
If you do an execute or a fetch using general selector (*) it works normally as follows:
` exports.oxmysql:execute("SELECT * FROM vrp_user_moneys WHERE user_id = :user_id",{user_id = 1},function(result)
        print(result)
end)`

However, if you execute an execute specifying a selector, it returns an error:
` exports.oxmysql:execute("SELECT wallet,bank FROM vrp_user_moneys WHERE user_id = :user_id",{user_id = 1},function(result)
        print(result)
end)`

Error: **Error: Unknow column 'walletNULL' in 'field list' SELECT wallet,bank FROM vrp_user_moneys WHERE user_id = :user_id**

If in Fetch:

Error: **Error: You have an error in your SQL syntax; check the manuel that corresponds to your MariaDB server version for the right syntax to use near ': FROM vrp_user_moneys WHERE user_id = ?**

**Comment by nyoakaway** [comment]
Using
`SELECT `wallet`,`bank` FROM `vrp_user_moneys` WHERE user_id = :user_id`
The code worked, but migrating 100% of sql is totally infeasible for any project!

**Comment by thelindat** [comment]
Is this error not being caused by the lack of spacing between wallet and bank? I'm using plenty of queries without wrapping identifiers in quotes.

**Comment by likizao** [comment]
> Using
> `` SELECT `wallet`,`bank` FROM `vrp_user_moneys` WHERE user_id = :user_id ``
> The code worked, but migrating 100% of sql is totally infeasible for any project!
It **is not the best method**, but it can be a **temporary solution**,
_on_prepare_ method in vRP db driver, you can add something like this
 ````
if query:match('SELECT') and not query:match('*')  then 
		query = query:gsub(" FROM",'` FROM')
		query = query:gsub("SELECT ",'SELECT `')
		query = query:gsub("%,","`,`")
	end
```

**Comment by nyoakaway** [comment]
> Is this error not being caused by the lack of spacing between wallet and bank? I'm using plenty of queries without wrapping identifiers in quotes.


This worked, however adapting all scripts taking out the obfuscated ones is not feasible!

**Comment by nyoakaway** [comment]
> > Using
> > `` SELECT `wallet`,`bank` FROM `vrp_user_moneys` WHERE user_id = :user_id ``
> > The code worked, but migrating 100% of sql is totally infeasible for any project!
> 
> It **is not the best method**, but it can be a **temporary solution**,
> _on_prepare_ method in vRP db driver, you can add something like this
> 
> ```
> if query:match('SELECT') and not query:match('*')  then 
>    	query = query:gsub(" FROM",'` FROM')
>    	query = query:gsub("SELECT ",'SELECT `')
>    	query = query:gsub("%,","`,`")
>    end
> ```

I've done this, but it's not at all advisable due to the amount of query you would have to do every little bit!

**Comment by likizao** [comment]
> > > Using
> > > `` SELECT `wallet`,`bank` FROM `vrp_user_moneys` WHERE user_id = :user_id ``
> > > The code worked, but migrating 100% of sql is totally infeasible for any project!
> > 
> > 
> > It **is not the best method**, but it can be a **temporary solution**,
> > _on_prepare_ method in vRP db driver, you can add something like this
> > ```
> > if query:match('SELECT') and not query:match('*')  then 
> >    	query = query:gsub(" FROM",'` FROM')
> >    	query = query:gsub("SELECT ",'SELECT `')
> >    	query = query:gsub("%,","`,`")
> >    end
> > ```
> 
> I've done this, but it's not at all advisable due to the amount of query you would have to do every little bit!

Yes, but it might be a temporary solution, it doesn't run very often and would only work on server startup.
I'm running like this and I haven't had problems or increased consumption so far.

**Comment by nyoakaway** [comment]
> if query:match('SELECT') and not query:match('*')  then 
>    	query = query:gsub(" FROM",'` FROM')
>    	query = query:gsub("SELECT ",'SELECT `')
>    	query = query:gsub("%,","`,`")
>    end

This solved the SELECT problem, but it didn't solve the others! Update 1.2.0 he made the change in the execute that some things like INSERT IGNORE or REPLACE is having problem not identifying the values ​​correctly!

**Comment by dunak-debug** [comment]
Try 1.3.0

**Comment by nyoakaway** [comment]
> Try 1.3.0

It almost worked, but if you still have no space in the request, it applies the error!

The sql is in the correct format being sent correctly! It has also been changed @ to : for testing, but it doesn't work!

![Error](https://imgur.com/a/YueUQYK "Error")

**Comment by dunak-debug** [comment]
![image](https://user-images.githubusercontent.com/19434539/133946369-ad015191-0bd2-405b-b39b-61f633f493eb.png)

That´s not valid query.

**Comment by nyoakaway** [comment]
> ![image](https://user-images.githubusercontent.com/19434539/133946369-ad015191-0bd2-405b-b39b-61f633f493eb.png)
> 
> That´s not valid query.

Here's the detail, if you look at the attached image, I showed that the query is being sent correctly (on top of the error there is a print of the query) later on this error occurs with this question!

Here is the query:
`INSERT IGNORE INTO vrp_user_moneys(user_id,wallet,bank) VALUES(@user_id,@wallet,@bank)`

**Comment by dunak-debug** [comment]
And whats the parameters values?

**Comment by nyoakaway** [comment]
> And whats the parameters values?
user_id = 1
wallet = 1000
bank = 2000



Note that in REPLACE there are also errors! But in version 1.1 everything was 100% functional! Her only problem was being boolean! But in other versions these problems started!

```REPLACE INTO vrp_user_data(user_id,dkey,dvalue) VALUES (@user_id,'nyo:GuardaRoupa',@value)
Error calling system tick function in resource oxmysql: Error: Undefined parameter dkey```

**Comment by nyoakaway** [comment]
> And whats the parameters values?


I just ran a test and identified the problem...

This gives an error:
```INSERT IGNORE INTO vrp_user_moneys(user_id,wallet,bank) VALUES(@user_id2, @wallet2, @bank2)```

This works:
```INSERT IGNORE INTO vrp_user_moneys(user_id, wallet, bank) VALUES(@user_id2, @wallet2, @bank2)```

He is not accepting the parameter pasted with the comma!

**Comment by dunak-debug** [comment]
Can you show me how you call this query in lua?

**Comment by thelindat** [comment]
> 
> 
> Is this error not being caused by the lack of spacing between wallet and bank? I'm using plenty of queries without wrapping identifiers in quotes.

I said this _5 days ago_. It's sanitising strings and it can't tell the comma shouldn't be a part of the column name.
![image](https://user-images.githubusercontent.com/65407488/133947367-e5745eb2-9228-430d-80d1-18fdff26c977.png)

The only thing to actually be fixed is that we don't accept `,` as a part of the column name, not your invalid queries. That's a bad looking query anyway.

`INSERT IGNORE INTO vrp_user_moneys(?, ?, ?) VALUES (?, ?, ?), {user_id, wallet, bank)`

**Comment by nyoakaway** [comment]
> Can you show me how you call this query in lua?

Not Working:
```exports.oxmysql:execute("INSERT IGNORE INTO vrp_user_moneys(user_id,wallet,bank) VALUES(@user_id2, @wallet2, @bank2)", {user_id2 = 1, wallet2 = 1000, bank2 = 2000 }, function(d)

end)```

Working:
```exports.oxmysql:execute("INSERT IGNORE INTO vrp_user_moneys(user_id, wallet, bank) VALUES(@user_id2, @wallet2, @bank2)", {user_id2 = 1, wallet2 = 1000, bank2 = 2000 }, function(d)

end)```


I deleted the content of the test so it wouldn't get too long! I made a direct fix on my connection DRIVE to automatically put a SPACE when there isn't one! This solved all the problems!

**Comment by thelindat** [comment]
> I deleted the content of the test so it wouldn't get too long! I made a direct fix on my connection DRIVE to automatically put a SPACE when there isn't one! This solved all the problems!
> 
> ```
> query = query:gsub("%,",", ")
> ```

🤦

**Comment by nyoakaway** [comment]
> > Excluí o conteúdo do teste para que não demorasse muito! Fiz uma correção direta na minha conexão DRIVE para colocar automaticamente um ESPAÇO quando não houver um! Isso resolveu todos os problemas!
> > ```
> > query = query:gsub("%,",", ")
> > ```
> 
> 🤦

This is not ideal, however as I am doing something that is not for a specific code, but for the VRP drive, I don't have access to all the queries from all the developers to put a single space after the comma! Unfortunately when working for something global, there's no way to think of 1 case (which was the one I showed) imagine every day a new developer put space, I don't have contact with all of them to adapt!

This turns out to be complicated and requires "adaptations" to work!

**Comment by thelindat** [comment]
Why are people not putting spaces between their column names is the real question.

![image](https://user-images.githubusercontent.com/65407488/133947776-6ec484e9-19fd-40f4-b4de-1450b9a28e2d.png)

Obviously we're not going to support weird column names like that, but putting a space between column names seems pretty logical to me.

**Comment by nyoakaway** [comment]
> Por que as pessoas não colocam espaços entre os nomes das colunas é a verdadeira questão.
> 
> ![imagem](https://user-images.githubusercontent.com/65407488/133947776-6ec484e9-19fd-40f4-b4de-1450b9a28e2d.png)
> 
> Obviamente, não vamos oferecer suporte a nomes de colunas estranhos como esse, mas colocar um espaço entre os nomes das colunas parece muito lógico para mim.

Well, all of the sql that we have until today gives this support, ghmatti, mysqlasync, as I said, it's not something for me but for everyone today who uses VRP(ex)!

The adaptation I made there worked, but it's not ideal!

About why people don't put space, I don't know, but this is the most common thing in the VRP(ex) community is you get a lot of scripts, bases and even developers that do this!

Apart from the obfuscated scripts that there isn't much to do!

It's up to you to judge this! It is not a bad practice not to put a space, this is quite common in other languages!

**Comment by thelindat** [comment]
> but this is the most common thing in the VRP(ex) community

Everybody in the ESX community looped through each xPlayer in a single tick, but that doesn't make it good practice. I don't think we should add support for no-spaces so that workaround for the VRP driver will have to do.

**Comment by nyoakaway** [comment]
> > mas isso é a coisa mais comum na comunidade VRP (ex)
> 
> Todos na comunidade ESX percorreram cada xPlayer em um único tique, mas isso não é uma boa prática. Não acho que devamos adicionar suporte para sem espaços para que uma solução alternativa para o driver VRP tenha que servir.


Remembering that this is not just for VRP, if a developer in esx/qbus or whatever language does not put space, simply won't be able to use oxmysql? So just sticking with others? Ox has a very good design, with an extremely high gain next to the others! But I think you should evaluate this question!

**Comment by thelindat** [comment]
If they're using oxmysql then they are expected to update their old queries as it is, so they should be ensuring proper usage at that time. It shouldn't be our responsibility to fix improper usage or maintain 100% compatibility with ghmatti/mysql-async (which was never the original intention in the first place).

You can make do with modifying those older resources to use `ScheduleResourceTick` and utilise promises for improved response times rather than fixing bad queries if that is preferable. We're using a different package that provides other benefits such as _actual_ async queries with promises (this is what throws a bunch of query time warnings if you send dozens through at once).

**Comment by nyoakaway** [comment]
> Se eles estiverem usando oxmysql, eles devem atualizar suas consultas antigas como estão, portanto, devem garantir o uso adequado naquele momento. Não deve ser nossa responsabilidade consertar o uso impróprio ou manter 100% de compatibilidade com ghmatti / mysql-async (que nunca foi a intenção original em primeiro lugar).
> 
> Você pode modificar esses recursos mais antigos para usar `ScheduleResourceTick`e utilizar promessas de exportações de sincronização para tempos de resposta melhores, em vez de corrigir consultas incorretas, se preferir. Estamos usando um pacote diferente que oferece outros benefícios, como consultas assíncronas _reais_ com promessas (isso é o que gera um monte de avisos de tempo de consulta se você enviar dezenas de uma vez).
> 
> As únicas coisas que precisam ter um desempenho semelhante são previsões de digitação e retornos de chamada.


Sorry, you say INAPPROPRIATE SQL, but there is no such definition... I'm sorry but you're wrong in wanting you to adapt something that we don't even have access to because of something you consider inappropriate! Thanks someone to change things to your liking being that the MYSQL itself accepts this, as it is something inappropriate?! your statement makes no sense! But thanks for the reply! Have a good night!

**Comment by thelindat** [comment]
> MYSQL itself accepts this

Since you want to argue about what mysql accepts, how about we talk about things it doesn't accept? Named parameters are an implementation of the node package and only support using `:`. Dunak has added support for `@` since that's what people generally use. There are use-case scenarios where named parameters are more useful, but only when you have a query that references the same parameter multiple times.

`INSERT INTO ox_inventory (owner, name, data) VALUES (:owner, :name, :data) ON DUPLICATE KEY UPDATE data = :data`
`SELECT owner FROM owned_vehicles WHERE plate = ?`

If you would like, we can remove named parameters entirely to be more inline with mysql's vision?

By the way, this works and is far less contrived.
```sql
exports.oxmysql:execute("INSERT IGNORE INTO vrp_user_moneys (??,??,??) VALUES (?,?,?)", {user_id, wallet, bank, 1, 1000, 2000}, function(d)

end)
```
Still massively questioning this insert ignore into crap.

**Comment by thelindat** [comment]
Your concern is duly noted.
![image](https://user-images.githubusercontent.com/65407488/133957552-dd2d6599-0d22-4cd9-9ca6-fed903bc63cd.png)
