### ISSUE TITLE
es_extended was unable to execute a query!

### ISSUE THREAD

**Issue by Vipex-Katar** [overextended/oxmysql#181]
[  script:es_extended] SCRIPT ERROR: @es_extended/server/main.lua:125: es_extended was unable to execute a query!
[  script:es_extended] Unknown column 'metadata' in 'field list'
[  script:es_extended] SELECT `accounts`, `job`, `job_grade`, `group`, `position`, `inventory`, `skin`, `loadout`, `metadata`, `firstname`, `lastname`, `dateofbirth`, `sex`, `height` FROM `users` WHERE identifier = ?
[  script:es_extended] > loadESXPlayer (@es_extended/server/main.lua:125)
[  script:es_extended] > handler (@es_extended/server/main.lua:29)
[  script:es_extended] > <unknown> (@oxmysql/dist/build.js:22053)
[  script:es_extended] > processTicksAndRejections (node:internal/process/task_queues:96)
![Cfx re Server (FXServer_unknown) - ^4Kurdish Xlife Roleplay 6_12_2023 12_41_18 PM](https://github.com/overextended/oxmysql/assets/111437842/f7e682de-4689-45fc-a9e9-e1668bcae3c6)

**Comment by thelindat** [comment]
Ask ESX.
