### ISSUE TITLE
no such export select in resource oxmysql

### ISSUE THREAD

**Issue by WolfBullet** [overextended/oxmysql#182]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I found this report "https://github.com/overextended/oxmysql/issues/154" and got the latest version via the provided link just to be sure and still got the same error.
I'm trying to do a simple select on a table. I'm working on a FiveM server. 

**Code**
```LUA
local data = MySQL.Select.await('Select * from player_vehicles where citizenid = ? AND vehicle = ?', {
        cid,
        vehicleModel
    })
```

**Expected behavior**
I get the data from the table

**Additional context**

**Server details**
- FXServer artifact: 6461
- Operating system: linux 6.0.9-060009-generic

**Database details**
- MariaDB
- Version 10.6.8-MariaDB

**Comment by LukeWasTakenn** [comment]
#154

**Comment by thelindat** [comment]
...

Select doesn't exist as an export because it is not and has never been an export, or a function.

**Comment by WolfBullet** [comment]
omg i did not see i wrote mysql.select wow how did i not spot that
