### ISSUE TITLE
malformed asynchronous insert query crashes servers

### ISSUE THREAD

**Issue by FrazzIe** [overextended/oxmysql#184]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Executing an async insert query that references an invalid table, column or provides bad data will outright kill node and crash the server.

**Screenshots**
Crash output from repro:
![Image of crash from repro](https://i.imgur.com/bRTfhEV.png)
**Code**
```lua
AddEventHandler('onResourceStart', function(resourceName)
    if GetCurrentResourceName() ~= resourceName then
        return;
    end

    -- -- await works fine
    -- local insert = MySQL.insert.await('INSERT into bad_query_table (col_1, col_2, col_3, col_4, col_5) VALUES (?, ?, ?, ?, ?)', {
    --     1, 5, 8, 'bad', true
    -- });

    -- -- works fine
    -- local query = MySQL.query.await('SELECT col_1, col_2, col_3, col_4, col_5 FROM bad_query_table WHERE col_1 = ?', { 1 });

    -- -- works fine
    -- MySQL.query('SELECT col_1, col_2, col_3, col_4, col_5 FROM bad_query_table WHERE col_1 = ?', { 1 });

    -- this kills the whole server
    MySQL.insert('INSERT into bad_query_table (col_1, col_2, col_3, col_4, col_5) VALUES (?, ?, ?, ?, ?)', {
        1, 5, 8, 'bad', true
    });
end)
```

**Expected behavior**
- Blasts the error in console but doesn't crash the server in the process

**Server details**
- FXServer artifact: latest,6511
- OS: Windows 10 (local) & Microsoft Windows Server 2019 Datacenter (server)

**Database details**
Tested on:
- 10.4.22-MariaDB (server)
- 10.10.2-MariaDB-1:10.10.2+maria~ubu2204 (local)

**Comment by thelindat** [comment]
On FXServer 6494
![image](https://github.com/overextended/oxmysql/assets/65407488/91345842-0e4f-477f-91cb-59423cbba6da)

On 6511
![image](https://github.com/overextended/oxmysql/assets/65407488/1823c3d5-5683-4c77-ad2c-3f1ed5f61f2e)

No crash in either case.

**Comment by FrazzIe** [comment]
hmm, not really sure then? I can repro it on a barebones server with cfx defaults & oxmysql. I'm also running it through txadmin.

barebones resource list:
```
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap
ensure baseevents

ensure oxmysql
```

**Comment by FrazzIe** [comment]
tried it on a barebones server without txadmin and it never killed the server, I believe it's reproduceable when running through txAdmin

**Comment by thelindat** [comment]
Not crashing on txAdmin here.

![image](https://github.com/overextended/oxmysql/assets/65407488/bce70abe-2f0f-4b55-b9c6-b85eb8209246)

Either way you can try building from source and see if the tweak to error handling helps.

**Comment by FrazzIe** [comment]
Did some further investigating, this is an issue 100% specific to my setup, I had a rogue node option set `$env:NODE_OPTIONS = "--openssl-legacy-provider"` that I was using to circumvent a webpack issue at the time 😐.
