### ISSUE TITLE
[      script:oxmysql] Error: Ignoring invalid configuration

### ISSUE THREAD

**Issue by disclearing** [overextended/oxmysql#188]
[      script:oxmysql] Error: Ignoring invalid configuration option passed to Connection: . This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

**Comment by disclearing** [comment]
mysql://user:password@host:port/dbname right ?

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/commit/37a3a7cd0a4e6ea94fcf52227c071b28f60b8fcf
