### ISSUE TITLE
MySQL.insert.await  does not return array of inserted ids if insert multiple rows with a single query

### ISSUE THREAD

**Issue by MatinHQ** [overextended/oxmysql#189]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I have table called `charges_data` which I put structure picture in screenshot section and I want to insert multiple rows in a single query with `MySQL.insert.await` which I did properly but the issue is `MySQL.insert.await` only returns the first row Id now all of inserted rows

**Screenshots**
![image](https://github.com/overextended/oxmysql/assets/22664859/f20b3008-38c9-4dd1-977f-051dcf7bb3fe)
![image](https://github.com/overextended/oxmysql/assets/22664859/d2bf6d77-96a6-4373-8ab1-8c3c069571b4)

**Code**
```lua
    local function addChargesToPlayer(identifier, charges)
    local data = {}

    for i = 1, #charges do
        local thisCharge <const> = charges[i]
        local chargeData <const> = getChargeInfoByName(thisCharge.name)
        if not chargeData then goto skip end

        data[#data+1] = {identifier, chargeData.category, chargeData.name, thisCharge.type}
        ::skip::
    end

    return MySQL.insert.await('INSERT INTO `charges_data` (`identifier`, `category`, `name`, `type`) VALUES ?', {data})
end

RegisterCommand('addcharge', function(source, args, RawCommand)
    local xTarget = ESX.GetPlayerFromId(tonumber(args[1]))

    local data = addChargesToPlayer(xTarget.identifier, {
        {name = 'murder', type = 1},
        {name = 'murder_law', type = 1},
        {name = 'baqooo', type = 1}
    })
    
    print(json.decode(data), {indent = true})
end)
```

**Expected behavior**
It whould return array of inseted Ids

**Additional context**
Nope

**Server details**
- FXServer artifact: latest
- Operating system: ubuntu

**Database details**
10.3.38-MariaDB-0ubuntu0.20.04.1

**Comment by thelindat** [comment]
The result set for the query only contains the the _last insert id_ (like when using `SELECT LAST_INSERT_ID()`), which isn't something I can change. You have to use prepare/rawExecute, or create a stored procedure to run each insert separately and store `LAST_INSERT_ID()` in a temp table.
