### ISSUE TITLE
oxmysql error

### ISSUE THREAD

**Issue by savage1988** [overextended/oxmysql#190]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

**Screenshots**
![image](https://github.com/overextended/oxmysql/assets/140867806/0dac9dc4-c873-4bae-a8d9-eccc8dbfdb49)

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/issues/174

> [x ] I am using the latest release

That'd be a no, as **not a release**. https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip

**Comment by RogueOneTV** [comment]
I am having the same issue and I have downloaded the most recent release per GitHub.

**Comment by thelindat** [comment]
No you haven't.
