### ISSUE TITLE
New version problems with esx_multicharacters.

### ISSUE THREAD

**Issue by Meister-L** [overextended/oxmysql#191]
We use multicharacter that we release a slot as a standard. And more need to be unlocked. Since we have this set to 1, there are problems here when I want to use the latest version of oxmysql.

**Comment by thelindat** [comment]
What

**Comment by darksaid98** [comment]
> We use multicharacter that we release a slot as a standard. And more need to be unlocked. Since we have this set to 1, there are problems here when I want to use the latest version of oxmysql.

**Please fill out the bug report form!** You haven't provided information and only stated that you have an issue with the latest version.

**Comment by Meister-L** [comment]
Sorry totally overlooked!

## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ X] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ X] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
With the latest version, esx_multicharacter does not establish a connection to the database!

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code**
```lua
    NO CODE
```

**Expected behavior**
that the connection is established.

**Additional context**
We use esx_multicharacter as 1 slot. Which will then be expanded via the database with further slots if this is approved!

**Server details**
-  v6.0.2 atop FXServer 6593 
-Ubuntu Linux 22.04.2

**Database details**
- MariaDB-Version 10.6.12

**Comment by thelindat** [comment]
> With the latest version, esx_multicharacter does not establish a connection to the database!

esx_multicharacter _doesn't_ establish a connection. ESX did however add some stupid bad-logic into the resource that _incorrectly_ attributes other errors as a failed connection - which also led to [this PR](https://github.com/esx-framework/esx_core/pull/1095).

You need to look at the server console and see what _actual_ error is preventing players from joining your server.
