### ISSUE TITLE
Missing close button on the ui page

### ISSUE THREAD

**Issue by prdatur** [overextended/oxmysql#192]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Mysql ui once open can not be closed.

**Screenshots**
-

**Code**
```lua
    -- no code
```

**Expected behavior**
There should be an X or Close button somewhere

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
![image](https://github.com/overextended/oxmysql/assets/65407488/fd4b402c-0a10-4677-9d65-4abc7621f19d)
