### ISSUE TITLE
Oxmysql error in multichar resource prevents joining to server (onReady)

### ISSUE THREAD

**Issue by SneakyAF** [overextended/oxmysql#195]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [?] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Since the update to the latest release I cannot join my own server because of an error in a resource.

The error originates from the another resource, however, only since the update to the latest version it prevents me from joining the server.
Before it just complained about not being able to alter certain database fields because of their length, but still allowed joining in. (Please check screenshots)

**Screenshots**
2.7.3
![image](https://github.com/overextended/oxmysql/assets/45791897/441a6c18-edb8-49c9-8135-84324cfc2ff6)
2.7.2
![image](https://github.com/overextended/oxmysql/assets/45791897/a5dc4466-0e26-4ee9-9f35-d67f0152aca9)

**Code**
    Sadly the resource is under escrow... So my only hope is to tackle this from the oxmysql side

**Expected behavior**
Despite the fail to alter the table no additional errors are generated causing the prevention to join the server.

**Additional context**
I do understand that this originates from another resource and I'm fine with downgrading the oxmysql version if there's nothing you can do about it. Thank you for at least reading about the issue.

**Server details**
- FXServer artifact 6461
- Operating system Windows 10

**Database details**
- MariaDB or MySQL MariaDB
- Version 11.1.0

**Comment by N-fire** [comment]
Not an issue with oxmysql, change your db setting for the column identifier, varchar 46 is too low change it to 50

**Comment by SneakyAF** [comment]
Unfortunately I need that field to be the length it is right now.

As I've stated above the error was always there and I'm fine with it as long as there aren't additional problems that prevent properly loading into the server which there are with the latest update.
