### ISSUE TITLE
Erreur executeSync

### ISSUE THREAD

**Issue by Maro089** [overextended/oxmysql#197]
j'ai un script qui a besoin de executeSync mais il n'y est plus dans la dernière version de oxmysql si quelqu'un peut me dire comment faire ducoup

**Comment by N-fire** [comment]
Pour votre gouverne cher compatriote, Napoléon a chu. Le monde ne maitrise point notre parlé supérieur.
Nous devons donc nous abaisser a parler ce perfide langage d'outre-manche qu'est l'anglais.
Navré de vous imposer un tel déshonneur.

Mes salutations distinguées.
Nfire

**Comment by PlouffeLuL** [comment]
Omg

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by darksaid98** [comment]
> j'ai un script qui a besoin de executeSync mais il n'y est plus dans la dernière version de oxmysql si quelqu'un peut me dire comment faire ducoup

The issues section does not exist to spoon-feed you code.
Please read the documentation: https://overextended.dev/oxmysql/Functions/rawExecute or review open-source projects that use OxMySQL.

Also, please ask in English next time.

**Comment by darksaid98** [comment]
> Pour votre gouverne cher compatriote, Napoléon a chu. Le monde ne maitrise point notre parlé supérieur. Nous devons donc nous abaisser a parler ce perfide langage d'outre-manche qu'est l'anglais. Navré de vous imposer un tel déshonneur.
> 
> Mes salutations distinguées. Nfire

Based take.
