### ISSUE TITLE
sync functions throws a nasty error

### ISSUE THREAD

**Issue by benzon** [overextended/oxmysql#2]
So today i decided to test oxmysql just to see how quick it is and if i wanna integrate it with alls cripts.

But found one major issue so fare, did a very very simple test.

```
local affectedRows = exports.oxmysql:executeSync('INSERT INTO testdb (name, data) VALUES (:name, :data)', {
    ['name'] = 'nisse',
    ['data'] = 'ged'
})

print('Updated '..affectedRows..' rows')
```

This resulted in a nasty error

```
[ script:drp_mechanic] Error loading script server/main.lua in resource drp_mechanic: citizen:/scripting/lua/scheduler.lua:1129: An error happened while calling export executeSync of resource oxmysql (attempt to yield from outside a coroutine), see above for details
[ script:drp_mechanic] stack traceback:
[ script:drp_mechanic]  [C]: in function 'error'
[ script:drp_mechanic]  citizen:/scripting/lua/scheduler.lua:1129: in function <citizen:/scripting/lua/scheduler.lua:1126>
[ script:drp_mechanic]  (...tail calls...)
[ script:drp_mechanic]  @drp_mechanic/server/main.lua:68: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource drp_mechanic
cfx> [ script:drp_mechanic] SCRIPT ERROR: cannot resume non-suspended coroutine
```

**Comment by benzon** [comment]
Okay might have figured it out, you actually need a CreateThread wrapper around the SQL call for it to not give this error.

```
Citizen.CreateThread(function()
    local affectedRows = exports.oxmysql:executeSync('INSERT INTO testdb (name, data) VALUES (:name, :data)', {
        ['name'] = 'nisse',
        ['data'] = 'ged'
    })
    print('Updated '..affectedRows..' rows')
end)
```

**Comment by thelindat** [comment]
Why do you need to use executeSync in this situation?

Typically useful for halting the rest of your code and keeping the result scope accessible to the rest of the code. Since you're putting it inside CreateThread, just perform a standard execute.

```lua
exports.oxmysql:execute('INSERT INTO testdb (name, data) VALUES (?, ?)', { 'nisse', 'ged'}, function(result)
     print('Updated '..result..' rows')
end)
```

We're returning lua promises when using the sync wrapper to reduce the delayed response that you would normally get with ghmattimysql (basically doubles the response time).

**Comment by thelindat** [comment]
```lua
local function executeSync(query, parameters)
    local p = promise.new()
    exports['oxmysql']:execute(query, parameters, function(result)
        p:resolve(result)
    end)
    return Citizen.Await(p)
end
```
Creates a new promise, triggers the standard execute, then returns a function reference to the promise; once execute completes it resolves the promise and the result is sent immediately.

The promise is essentially `while unresolved do Wait(0) end`.

**Comment by benzon** [comment]
Ye i know that, it was just a test, to compare to Mysql-Async's Sync function to see the speed differences, trying to figure out the performance changes oxmysql will bring on the table compared to mysql-async.
