### ISSUE TITLE
simply spamming when a player connects to server

### ISSUE THREAD

**Issue by Harry755** [overextended/oxmysql#204]
[      script:oxmysql] Error: esx_datastore was unable to execute a query!
[      script:oxmysql] Query: INSERT INTO datastore_data (name, owner, data) VALUES (?, ?, ?)
[      script:oxmysql] ["user_glasses","char1:bbf8bef6ec672db6b82f9f75a523396e56c13f26","{}"]
[      script:oxmysql] Duplicate entry 'user_glasses-char1:bbf8bef6ec672db6b82f9f75a523396e56c13f26' for key

**Comment by darksaid98** [comment]
This is not an issue with oxmysql but with the resource `esx_datastore`. Please request support from the maintainer or maker of that resource.

When reporting bugs it would be appreciated if you fill out the form 👍
