### ISSUE TITLE
OXMYSQL error No such export query in resource oxmysql

### ISSUE THREAD

**Issue by Gavin1706** [overextended/oxmysql#208]
![Screenshot 2023-11-17 183350](https://github.com/overextended/oxmysql/assets/151119369/a47a4933-d730-4819-8660-8f4cabcebe8e)
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
After I updated my oxmysql and my ox_lib a bunch of my scripts stopped working. I do not know how to fix it. It could be a easy fix but I am still new to development and I am still learning and any help would be great if anyone knows whats happening. Please help me.  

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by xxUnknown13xx** [comment]
How you fixed yours?
