### ISSUE TITLE
OXmysql link download isn't updating to version v2.7.6

### ISSUE THREAD

**Issue by sgheemamasavage** [overextended/oxmysql#209]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I am showing that I needed to update the oxmysql to the newest version, however, when I download the latest version it still shows that I am using v2.7.5

**Screenshots**
![image](https://github.com/overextended/oxmysql/assets/121644501/c37354bc-f63e-412f-bb98-16d88e38b5c9)
https://media.discordapp.net/attachments/1069235438637813863/1176191308444999750/image.png?ex=656df884&is=655b8384&hm=87ed552e1aa37b82af545097e003a9826b6883ab6c9b99033c3ea5b3d3af055e&=&width=564&height=56

**Code** n/a
```lua
    -- If applicable, include the query and relevant code
```

**Link Referenced**
Link I am using to update version:
https://github.com/overextended/oxmysql/releases/download/v2.7.6/oxmysql.zip

**Expected behavior**
Trying to update to the latest version and live console still shows that I have v2.7.5

**Additional context**
I am unable to access player inventory, I can't even pull out player phone.

**Server details**
- FXServer artifact: txAdmin FiveM server
- Operating system: Windows

**Database details**
- MariaDB or MySQL (I am a little confused by this because I use MariaDB via phpmyadim to configure database and I am using MySQL via OxMySQL for inventory, fuel, lib, etc...)
- Version: FXServer-master v1.0.0.7114 linux
- txAdmin Version: 6.0.2

**Comment by jag3dagster** [comment]
I just downloaded the 2.7.6 release and am not getting this issue. Likely user error somewhere along the way.

**Comment by sgheemamasavage** [comment]
which link did you click?
oxmysql.zip
source code (zip)
source code (tar.gz)

**Comment by jag3dagster** [comment]
oxmysql.zip

**Comment by sgheemamasavage** [comment]
well, not sure how I am still getting the message that there is an update available if I used the same link. Just redownloaded link and it still shows that v2.7.6 is avail and that I have v2.7.5... smh

**Comment by sgheemamasavage** [comment]
this is what is in fxmanifest... but isn't reflected on Live Console that it is updated version....

name 'oxmysql'
description 'Database wrapper for FXServer utilising node-mysql2 offering improved performance and security.'
version '2.7.6'
url 'https://github.com/overextended/oxmysql'
author 'overextended'

dependencies {
	'/server:5104',

**Comment by jag3dagster** [comment]
Then you either have a second installation of oxmysql that is actually getting started or you're otherwise not using the files you think you are.

**Comment by sgheemamasavage** [comment]
I will do a search to see if there is a duplication of the oxmysql in my resource folder. Otherwise, I am confident that I am using the link within the first post I made above. Not rocketscience with that task is required for sure, lol. Thank you for your help. Hopefully once you used the link you are able to see it reflected in your live console, correct?

**Comment by sgheemamasavage** [comment]
thank you. That was it. There was a duplicate oxmysql.

**Comment by sgheemamasavage** [comment]
resolved.
