### ISSUE TITLE
Fatal Error.. Entering v8 api without proper locking in place.

### ISSUE THREAD

**Issue by tony-stark-17** [overextended/oxmysql#21]
Fatal Error.. Entering v8 api without proper locking in place. Gives this error and the server shutsdown

**Comment by dunak-debug** [comment]
Server artifact version?

**Comment by tony-stark-17** [comment]
4162

**Comment by dunak-debug** [comment]
Try to update to at least recommended 4394, I think this was fixed while ago

**Comment by thelindat** [comment]
Always use the latest recommended server artifact _at a bare minimum_ - we're up to 4394. Use even more recent for newer features and potentially breaking changes if you're ballsy, but never outdated.
