### ISSUE TITLE
Connection Timeout When Starting Up Server Since v2.7.6

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [overextended/oxmysql#210]
- [X] I am using the latest release
- [X] I have referenced previously reported issues
- [X] I have referenced available documentation and cannot resolve the issue
- [X] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I just updated to [v2.7.6](https://github.com/overextended/oxmysql/releases/tag/v2.7.6) from v2.7.5.

Suddenly oxmysql refuses to connect during server startup and I have to manually restart oxmysql every time which then connects right away, and I then must start up 40+ other dependencies of course that use it.

This did not happen on v.2.7.5.

I've never had this issue until now. I even tried moving my ox resources to the top of my server.cfg to see if that would do the trick. No dice. The startup time is the same as always.

I am posting this because I noticed some things were changed with connection to the database on this release. ( https://github.com/overextended/oxmysql/commit/0398abc501453098823244a1bfe93bb27091b538 ) Perhaps its related. Since thats the exact issue I'm having.

```
[      script:oxmysql] Unable to establish a connection to the database (ETIMEDOUT)!
[      script:oxmysql] Error undefined: connect ETIMEDOUT
```

**Expected behavior**
For oxmysql to be able to connect to database to connect on startup as normal.

**Server details**
- FXServer artifact: v6.0.2 atop FXServer 7130
- Operating system Windows Server 2022

**Database details**
- 10.4.28-MariaDB

**Comment by Eridau** [comment]
Can confirm I am experiencing this problem as well.

**Comment by blakelyrachelle** [comment]
i get this error with this version: SCRIPT ERROR: No such export execute in resource ghmattimysql

**Comment by Legacy-TacticalGamingInteractive** [comment]
> i get this error with this version: SCRIPT ERROR: No such export execute in resource ghmattimysql

yeah i saw that one as well

**Comment by KentaKK** [comment]
I've experienced the same, it only connects after 2-3 restart, when loading can be fast enough to connect

**Comment by Legacy-TacticalGamingInteractive** [comment]
Temporary fix is to revert back to previous version: https://github.com/overextended/oxmysql/releases/tag/v2.7.5

**Comment by AlexGThess** [comment]
same issue here.

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/commit/3fef91800039fbb09a6c60642211cf11e7522d8a

**Comment by KentaKK** [comment]
Thanks

**Comment by AlexGThess** [comment]
2.7.7 seems resolved it.

**Comment by KentaKK** [comment]
Sure is
![0001](https://github.com/overextended/oxmysql/assets/102387086/35a38a26-8ab4-4447-92f1-0b201615dcf5)
