### ISSUE TITLE
Database is not established in FIVEM.(EAI_AGAIN)

### ISSUE THREAD

**Issue by o1tan** [overextended/oxmysql#212]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [✓ ] I am using the latest release
- [ ✓] I have referenced previously reported issues
- [✓ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

It used to work, but after initializing and rebuilding the server, oxmysql no longer establishes the database.

**Screenshots**
![スクリーンショット 2024-01-16 154322](https://github.com/overextended/oxmysql/assets/156775090/f75232df-386f-4238-996b-3b653352d3c3)
![スクリーンショット 2024-01-16 165728](https://github.com/overextended/oxmysql/assets/156775090/8bc3f871-504a-48f2-a599-cf68a9605d1e)

**Code**
```lua
    -- If applicable, include the query and relevant code
```
See screenshot above.
**Expected behavior**
The fivem server is not working.
**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version
MariaDB　Version10.3.38

**Comment by thelindat** [comment]
Generic DNS or networking issue, unrelated to the resource.

**Comment by o1tan** [comment]
How can I improve it?
