### ISSUE TITLE
Bug new update

### ISSUE THREAD

**Issue by IceColdfm** [overextended/oxmysql#214]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by IceColdfm** [comment]
after updating the latest version.

I have these messages in my server cfg.
in the previous version and had no problems with it before.

![ox](https://github.com/overextended/oxmysql/assets/119862447/63593f5d-65ff-4c11-8c1c-63216dbd69a9)

**Comment by thelindat** [comment]
That's a slow query warning. It was temporarily disabled unless ui was enabled (https://github.com/overextended/oxmysql/commit/45aadf744261a7d546635afaa6dc1a082cea06ad) but added back in with https://github.com/overextended/oxmysql/commit/e31d84019ec28e6df649f440a8fe24b0c873d994.

You can generally ignore it if it's just on startup.
