### ISSUE TITLE
most recent update

### ISSUE THREAD

**Issue by blakelyrachelle** [overextended/oxmysql#215]
[ script:vorp_mailbox] SCRIPT ERROR: @vorp_mailbox/server/server.lua:192: No such export execute in resource ghmattimysql
[script:bcc-legendari] SCRIPT ERROR: @bcc-legendaries/server.lua:49: No such export execute in resource oxmysql
[  script:syn_farming] SCRIPT ERROR: No such export execute in resource ghmattimysql
[script:mega_doctorjo] SCRIPT ERROR: No such export executeSync in resource ghmattimysql
[      script:gum_mdt] SCRIPT ERROR: No such export execute in resource ghmattimysql
[     script:gum_jail] SCRIPT ERROR: No such export execute in resource ghmattimysql

was working fine before update to latest

**Comment by thelindat** [comment]
Ensure you are downloading the release build from https://github.com/overextended/oxmysql/releases/download/v2.8.0/oxmysql.zip

**Comment by Beaker9191** [comment]
even downloading from there i get the same issue

**Comment by xhackax47** [comment]
Same for me, ive tried to download the release and ive No Such Export issues on many scripts who were OK before the upload
