### ISSUE TITLE
no fxmanifest

### ISSUE THREAD

**Issue by npicard301** [overextended/oxmysql#216]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
The update doesn't have a fxmanifest

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/releases/download/v2.9.0/oxmysql.zip

![image](https://github.com/overextended/oxmysql/assets/65407488/507dd65a-7d12-4954-8a3f-d6e94bb2ba49)

Why is this so difficult?
