### ISSUE TITLE
2.9.0 update issue

### ISSUE THREAD

**Issue by Demp3** [overextended/oxmysql#217]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
When I updated from 2.8.0 to 2.9.0 I get an error like the one attached in the console for most of my resources.

If I revert back to 2.8.0 they all load normally.  It would be helpful if you had instructions on how to simply update the resource.  I know it might seem trivial to some, but apparently I am doing something wrong.

**Screenshots**
![image](https://github.com/overextended/oxmysql/assets/155211853/44d3e9b1-e2b0-41d4-9ac3-88e88fbc6da1)

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**
1. I unzipped and overwrote the files in the oxmysql folder. I expected it would update.  It did not update it.
2. I completely removed the existing contents of the oxmysql folder and unzipped the contents of 2.9.0.  I expected that might update it.  It did not update it.

**Additional context**

**Server details**
- FXServer artifact - 7549
- Operating system - Win 10 Pro

**Database details**
- MariaDB or MySQL - xampp with Heidi & Maria
- Version Heidi = 12.6.0.6765,  xampp = 8.2.12, Maria = Could not locate to get version number.

**Comment by Demp3** [comment]
Just updated artifacts to 7568 with no change.  I have reverted back to 2.8.0.

**Comment by tom-osborne** [comment]
Make sure you are downloading the release, not the source code.

![image](https://github.com/overextended/oxmysql/assets/96954031/f38d4f98-0722-4094-a08c-8c6ec9ec91ca)

**Comment by Demp3** [comment]
Well that's not a noob mistake, right?  That fixed it.  Thank you!

**Comment by Demp3** [comment]
I'm sure that goes for a lot of these other resources too.
