### ISSUE TITLE
 Unable to establish a connection to the database (EAI_AGAIN)!

### ISSUE THREAD

**Issue by Der-Komische** [overextended/oxmysql#218]
i got an script error
[      script:oxmysql] Error -3001: getaddrinfo EAI_AGAIN root
[      script:oxmysql] Error: Ignoring invalid configuration option passed to Connection: @xxx.xxx.x.xxx/ESXLegacy_xxxxxx?charset. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

**Comment by thelindat** [comment]
Not a resource issue.
