### ISSUE TITLE
oxmysql v2.10.0 Unable to determine current resource version for 'oxmysql' 

### ISSUE THREAD

**Issue by ChaiyaZ-Dev** [overextended/oxmysql#221]
oxmysql v2.10.0 
![image](https://github.com/overextended/oxmysql/assets/70051176/28d80568-0bab-4662-a711-259de2ddd774)
Unable to determine current resource version for 'oxmysql'

**Comment by thelindat** [comment]
You can ignore it or update at your convenience.

**Comment by ChaiyaZ-Dev** [comment]
Hello,

Thank you for looking into this. The issue appears to be related to the regular expression used to extract the version number from the metadata. The current pattern /(\d)\.(\d)\.(\d)/ only matches single digits between dots, which is why it fails for versions with multi-digit numbers like '2.10.0'.

To resolve this, the regex should be updated to /(\d+)\.(\d+)\.(\d+)/ to accommodate any number of digits in the version sections. This change would ensure that versions like '2.10.0' are properly recognized.

Here’s the updated line of code for your reference:

`const currentVersion = (_a4 = GetResourceMetadata(resourceName2, "version", 0)) == null ? void 0 : _a4.match(/(\d+)\.(\d+)\.(\d+)/);
`

**Comment by thelindat** [comment]
> The issue appears to be related to the regular expression used to extract the version number from the metadata.

I already fixed this an hour ago and pushed the changes https://github.com/overextended/oxmysql/commit/68028f1f4e2848f39e4562c898691e5529cbf5dc.
