### ISSUE TITLE
(node:19) UnhandledPromiseRejectionWarning: Error: ak4y-dailyTasks was unable to execute a query!

### ISSUE THREAD

**Issue by Iprat007** [overextended/oxmysql#223]
![Screenshot 2024-05-22 230711](https://github.com/overextended/oxmysql/assets/128974650/d46a1681-dcf5-41b6-a815-e91790e48e9e)
  
 I have never had this issue before until yesterday, I reinstalled a back up that I have always used, but I can not get passed character name creation without an infinite black loading screen before I select a spawn. The scripts themselves do not seem to have any errors, I have tried to delete them (fs apartments, multicharacter), but I am having the same issue. The only errors I could think of that would be causing this is the ones I posted in the photo. I have tried to update to a later version oxMySQL but the server doesn't seem to detect it for some reason. So I use the one on my backup. I know it is probably an easy fix, as I am not too knowledgeable on SQL's and databases because I have always ran vmenu up until about 6 months ago. But I run a very successful server and people aren't able to join do to these errors. So any help would be appreciated.

**Comment by thelindat** [comment]
![image](https://github.com/overextended/oxmysql/assets/65407488/dbcadb09-390f-46cf-8267-6098a8297785)

Nothing to do with the resource - your database is missing table(s).
