### ISSUE TITLE
 Error -111: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by austinbatter** [overextended/oxmysql#224]
Anyone know how to fix "Error -111: connect ECONNREFUSED 127.0.0.1:3306"

**Comment by thelindat** [comment]
> using the latest version just use the non latest i spend nearly a hour & fixed it

How is downgrading a "fix"? If you have a reproducible issue and can actually provide information then I can do something about it, however nothing has changed with connections or the underlying driver used to connect to the mysql server.

> -- i've seen alot of people with the issue

The only other person (singular) that has recently reported ECONNREFUSED with this specific error number resolved it by changing their connection string (https://overextended.dev/oxmysql/issues#unable-to-establish-a-connection).
