### ISSUE TITLE
UnhandledPromiseRejectionWarning on fetching latest version

### ISSUE THREAD

**Issue by Exyztence** [overextended/oxmysql#225]
Hey,
I wanted to join my server but the Steam API was down and I received an error about no Steam running. I did "quit" in the console and that error below poped in the server-console. I've wanted to report it to you:)
Greetings

[              STDERR] (node:437926) UnhandledPromiseRejectionWarning: FetchError: request to https://api.github.com/repos/overextended/oxmysql/releases/latest failed, reason: getaddrinfo EAI_AGAIN api.github.com
[              STDERR]     at ClientRequest.<anonymous> (@oxmysql/dist/build.js:25706:14)
[              STDERR]     at ClientRequest.emit (node:events:394:28)
[              STDERR]     at TLSSocket.socketErrorListener (node:_http_client:447:9)
[              STDERR]     at TLSSocket.emit (node:events:394:28)
[              STDERR]     at emitErrorNT (node:internal/streams/destroy:157:8)
[              STDERR]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[              STDERR]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[              STDERR] (Use `FXServer --trace-warnings ...` to show where the warning was created)
[              STDERR] (node:437926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by thelindat** [comment]
Network or firewall issue; I'll just add a catch and ignore it.
