### ISSUE TITLE
Associative Arrays support

### ISSUE THREAD

**Issue by aidanohart** [overextended/oxmysql#228]
**Is your feature request related to a problem? Please describe.**
It's not necessarily a problem, but it would be a neat feature to have and appreciated very much by some.

**Describe the solution you'd like**
Would love a way where a query would autoamtically put the results into an associative array. For example, in PHP PDO you can do something along the lines of:

```php
$stmt = $pdo->prepare("SELECT id, name FROM users");
$stmt->execute();
$arr = $stmt->fetchAll(PDO::FETCH_KEY_PAIR);
```
Which `$arr` returns `[1 => 'User1Name', 2 => 'User2Name', 3 => 'User3Name']`

Something like this:
```lua
local characterMetadata = MySQL.query.keypair("SELECT type,value FROM `character_metadata` WHERE `character` = ?", { characterId })
```

**Describe alternatives you've considered**
Below is a Lua example of something I was doing which I remembered could do with PDO (php) so thought to look at docs to see if could do on oxmysql which has got me making this feature request.
```lua
local characterMetadata = {}
local metadata = MySQL.query.await("SELECT type,value FROM `character_metadata` WHERE `character` = ?", { characterId })
for k,v in pairs(metadata) do
    characterMetadata[v.type] = v.value
end
```

**Additional context**
I know it's small and probably pointless to some but I know there will be people that would appreciate this out there.

**Comment by thelindat** [comment]
https://mariadb.com/kb/en/json_objectagg/
