### ISSUE TITLE
Intergration with Fivemerr

### ISSUE THREAD

**Issue by rxnm** [overextended/oxmysql#233]
You have recently added (fivemanage) so why not add Fivemerr too? Here is the script to do so (attached) 

Thanks

[fivemerr.zip](https://github.com/user-attachments/files/16603183/fivemerr.zip)

**Comment by darksaid98** [comment]
Submitted a PR here: https://github.com/overextended/oxmysql/pull/235

**Comment by thelindat** [comment]
I won't be merging fivemerr support. I'm not going to get into the reasons here.
They are, of course, free to provide their own script file and instructions for setup.

**Comment by rxnm** [comment]
> I won't be merging fivemerr support. I'm not going to get into the reasons here. They are, of course, free to provide their own script file and instructions for setup.

Linden, whatever beef you have with Monkey is your guys problems, but this is nothing to do with that and does help a lot of people out, dunno why you just can't approve it. Oh well, its your say so or not. Thx anyway.

**Comment by thelindat** [comment]
> Linden, whatever beef you have with Monkey is your guys problems

I have _literally never_ spoken to the guy.

> but this is nothing to do with that

I have issues with fivemerr itself.

> dunno why you just can't approve it

Well, I already said I'm not going to get into the reasons here.

**Comment by rxnm** [comment]
Mate, if you have issues with it, just like you would tell anyone with OX stuff, report it and it will get seen too. Fivemerr is good, Monkey has done his best to listen to others and you can on his Discord for (Fivemerr) that he is willing to listen when there are issues.
