### ISSUE TITLE
Bug with affected rows with execute method

### ISSUE THREAD

**Issue by leekyrave** [overextended/oxmysql#234]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
When I use execute method(sync) and try to get Affected rows, I just get Affected Rows Matched, not changed.

**Screenshots**

**Code**
```lua
function Something:ChangeRank(personageID, newRank)
    local query = [[
        UPDATE `%s`
        SET rank = @newRank
        WHERE personage_id = @userID
    ]]

    query = string.format(query, ServerConfig.membersTableName);

    local affectedRows = MySQL.Sync.execute(query, {
        ['@newRank'] = newRank,
        ['@userID'] = personageID,
    });

    if affectedRows == 0 then
        return false;
    end

    return true;
end
```

**Expected behavior**
It have to return just CHANGED-Affected rows, not  matched.

**Additional context**
I think, it should be as stated above, cause I need to check if my row has been changed.(Two queries are unefficient)

**Server details**
- FXServer artifact - 
- Operating system

**Database details**
- MySQL
- 8.0.37

**Comment by thelindat** [comment]
The return values such as affectedRows come from your database, not oxmysql.

**Comment by leekyrave** [comment]
Thank you
