### ISSUE TITLE
oxmysql 

### ISSUE THREAD

**Issue by xE-1x** [overextended/oxmysql#236]
[      script:oxmysql] Warning: Failed to retrieve latest version of oxmysql (ECONNRESET).
[      script:oxmysql] Unable to establish a connection to the database (ECONNRESET)!
[      script:oxmysql] Error -104: write ECONNRESET

Just started getting this today after updating to the lew release. Never had any issues until this update

**Comment by juddisjudd** [comment]
This issue isn’t related to oxmysql itself. Please download the [latest release](https://github.com/overextended/oxmysql/releases/latest) and replace your current files. If the problem persists, double-check your connection string and verify your SQL database settings.
