### ISSUE TITLE
callback-style functions do not throw errors

### ISSUE THREAD

**Issue by AusHick** [overextended/oxmysql#237]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Using the callback-style functions for MySQL operations always return true in `pcall`, and have no other method of error handling. The promise-style functions **do not** have this issue, and will return false in `pcall`, with error result.

In this particular instance, the INSERT is attempted on a table that has not yet been created.

**Screenshots**
N/A

**Code**
```lua
print(pcall(MySQL.insert, "INSERT INTO player_ankle_monitors (serial, state, target, actor) VALUES(?, 1, ?, ?)",
	{
		keyItem.info.serial,
		qbClosestPlayer.PlayerData.citizenid,
		qbPlayer.PlayerData.citizenid
	},
	function(...)
		print("Query CB")
		print(arg)
		
		-- more code
	end))
```
The above returns `true`
Replacing `MySQL.insert` with `MySQL.insert.await` returns `false` and `RESOURCENAME was unable to execute a query!`

**Expected behavior**
Either the callback function should always be called and support error results as a second argument, or the callback should not be called and the MySQL function should return similarly to the promise counterpart.

**Additional context**

**Server details**
- FXServer artifact 7290
- Windows 10 x64

**Database details**
- MariaDB
- 11.5.2

**Comment by thelindat** [comment]
This is how mysql-async worked, and so that behaviour was adopted for the sake of compatibility. Changing it would break thousands of scripts using callbacks and expecting a response only when the query was successful.

I can't just use a promise for every query either - callbacks should not block the current thread.

**Comment by AusHick** [comment]
> This is how mysql-async worked, and so that behaviour was adopted for the sake of compatibility. Changing it would break thousands of scripts using callbacks and expecting a response only when the query was successful.
> 
> I can't just use a promise for every query either - callbacks should not block the current thread.

There is still a fundamental issue of being unable to do error handling using callbacks, unless I'm missing something. I can understand forcing the query callback function to always be called could lead to issues in existing scripts where it's expected to run only during an error. Perhaps a second argument to the query callback isn't appropriate for those cases. 

Instead, how about support for a second callback function specifically for error handling? This is common in other implementations for SQL connectors. `MySQL.insert(query, params, onSuccess, onError)`? This will keep compatibility with existing scripts while enabling new ones.

Alternatively, I don't think changing the return value of the function should cause issues because it currently has no use or reason to be checked in older scripts. Though I prefer the above solution since it fits the callback style better.

**Comment by thelindat** [comment]
> I don't think changing the return value of the function should cause issues

`MySQL.insert` and such don't have any return values, and can't return if the query failed or succeeded since they return before the query is triggered.

> how about support for a second callback function specifically for error handling?

At some point, but it really isn't a concern at this time (considering you are the first person to be concerned about callback error handling).

**Comment by thelindat** [comment]
With the next release you can add options to fxmanifest.lua to change behaviour.
```lua
mysql_option 'return_callback_errors'
-- or
mysql_options {
    'return_callback_errors'
}
```
