### ISSUE TITLE
Update Dependency @citizenfx/server@2.0.10072 does not exist.

### ISSUE THREAD

**Issue by jvalore-nimblepros** [overextended/oxmysql#239]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [X] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

In this commit: https://github.com/overextended/oxmysql/commit/ab2d2834a3ba2b2684cd9699c13d9cd5f3584551
it looks like you switched `@citizenfx/server` to version `2.0.10072` which does not seem to exist.

This results in an error
```
Couldn't find any versions for "@citizenfx/server" that matches "2.0.10072"
```

The possible versions published to npm are: https://www.npmjs.com/package/@citizenfx/server?activeTab=versions so I'm guessing you probably meant to use `2.0.10072-1` (with a `-1` on the end).

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
> you probably meant to use 2.0.10072-1 (with a -1 on the end).

That's incredibly fun considering I didn't manually specify a version at all, but rather used `pnpm update`. Left very confused here.

**Comment by jvalore-nimblepros** [comment]
Interesting. Maybe `pnpm` infers the `-1` or something. `yarn` had issues with it 🤷 Anyway, thanks for taking a look.
