### ISSUE TITLE
Trojan H!ml please solved

### ISSUE THREAD

**Issue by phyroxneyver** [overextended/oxmysql#248]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by juddisjudd** [comment]
Read what you have posted here, do you think you have provided any info that would help someone else understand what issue you are facing?

**Comment by itsfaizy** [comment]
he means this. when downloading oxmysql.zip from releases for version 2.12.0

![image](https://github.com/user-attachments/assets/6d1c858d-1da9-4f58-a8f3-d32b8cc2b046)

**Comment by juddisjudd** [comment]
False positive
