### ISSUE TITLE
Server crash due to oxmysql

### ISSUE THREAD

**Issue by bylickilabs** [overextended/oxmysql#249]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

**Screenshots**

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Expected behavior**

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

|![ISSUE](https://github.com/user-attachments/assets/6b680cd5-9420-48d4-8589-6d53faf64d3a)|
|---|

```yarn
All attempts have failed!
Once again the server cannot be loaded because, as always, there is a problem with oxmysql! It is just nerve-wracking. 
The exception that crashes occur is unfortunately becoming the rule.

The problems only occurred with the new version.
Unfortunately, downgrading to the previous version does not change this fact.
The server is unchanged! Before you ask any questions, no work has even been done on it.
```

**Comment by thelindat** [comment]
> as always, there is a problem with oxmysql

Nice hostility.

> The problems only occurred with the new version.
> downgrading to the previous version does not change this fact.

So it occurs on the old version too, based on this statement.

---

Not sure why you can't fill out the issue form properly, but this is a generic error not caused by oxmysql. I'm sure you can figure out how to google "emfile".
