### ISSUE TITLE
Error: framework was unable to execute a query!

### ISSUE THREAD

**Issue by MacMellon1** [overextended/oxmysql#254]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x ] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
So basicly it try to find DB, but it cant and i dont know why

**Screenshots**
![image](https://github.com/user-attachments/assets/53eb37b0-873e-4f42-8b64-4725708c248d)

**Code**
[      script:oxmysql] Error: framework was unable to execute a query!
[      script:oxmysql] Query: SELECT * FROM characters WHERE id LIKE ?
[      script:oxmysql] ["%"]
[      script:oxmysql] Table 's13501_Sosaldata.characters' doesn't exist

**Expected behavior**
I try to make DB for npwd phone on hosting

**Additional context**
Erlier i make anything on local pc, and its work great

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB
- 10.11.10

**Comment by darksaid98** [comment]
This is not a bug in Oxmysql. 

Your query is trying to fetch data from a table (`characters`) that doesn't exist. Ensure that the database actually has the tables you are trying to query.
