### ISSUE TITLE
Async callback queries throw error on success

### ISSUE THREAD

**Issue by OMikkel** [overextended/oxmysql#257]
## Issue checklist

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Calling MySQL.Async.fetchAll with a successful query returns the expected result, but if an error happens (collation mismatch etc.) the error will only be logged to the console and nothing will be returned in the callback.
As a resource developer this is not very helpful as I would like to report an error message to user instead of just returning empty payload.

I then thought of calling it inside xpcall() https://www.lua.org/manual/5.4/manual.html#pdf-xpcall
When doing this it works as expected on errors - well it just returns (attempt to call nil value) on all errors, but it is better than nothing. The problem is that even when I run a successful query with no errors, the xpcall still returns (attempt to call nil value).

**Screenshots & Code**
This is a screenshot of an expected error with the code:
```lua
xpcall(MySQL.Async.fetchAll("SELECT * FROM playerwadad WHERE badge_number = @badge AND password = PASSWORD(@password)", {
    ["@badge"] = badge,
    ["@password"] = password
}, function(result)
    print("RESULT:", json.encode(result))
end), function(err)
    DebugPrint("DB_ERROR", err)
    return cb({
        success = false,
        error = L("ERRORS.DB_ERROR")
    })
end)
``` 
![Screenshot 2024-12-19 at 14 29 58](https://github.com/user-attachments/assets/2935a893-8394-4d69-9639-311189250373)

This is a screenshot and code of a successful query inside xpcall:
```lua
xpcall(MySQL.Async.fetchAll("SELECT citizenid FROM players", {}, function(result)
    print("RESULT:", json.encode(result))
end), function(err)
    DebugPrint("DB_ERROR", err)
    return cb({
        success = false,
        error = L("ERRORS.DB_ERROR")
    })
end)
```
![Screenshot 2024-12-19 at 14 31 59](https://github.com/user-attachments/assets/a5009db4-97a1-42eb-b2f8-36c16e71176d)

**Expected behavior**
I expect to be able to wrap the below code in xpcall and only catch errors when it doesn't work.
```lua
MySQL.Async.fetchAll("SELECT citizenid FROM players", {}, function(result)
    print("RESULT:", json.encode(result))
end)
```
![Screenshot 2024-12-19 at 14 33 59](https://github.com/user-attachments/assets/de96b474-fe8b-4098-8659-67065a4c262c)

**Server details**
- FXServer artifact
`12031/linux`
- Operating System:
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

```

**Database details**
- MariaDB 
- Version: `11.5.2`

**Comment by thelindat** [comment]
Did you read https://github.com/overextended/oxmysql/releases/tag/v2.12.0
