### ISSUE TITLE
How to define the connection Port?

### ISSUE THREAD

**Issue by FilipeQ** [overextended/oxmysql#29]
Hello,

I have my localhost database in the port 3308 but i tried to define it in the config but when I start the server the oxmysql cannot connect with the database.
I think this happens because the script use the default port 3306.

![Screenshot_1](https://user-images.githubusercontent.com/7237584/134599421-31aab2d2-143a-4f3b-a9a5-9416a778dbe0.jpg)

I tried the following connection strings:
set mysql_connection_string "mysql://user:password@localhost:3308/rs-test?charset=utf8mb4"

set mysql_connection_string "mysql://user:password@127.0.0.1:3308/rs-test?charset=utf8mb4"

set mysql_connection_string "mysql://localhost:3308/rs-framework?user=tets&password=test123"

How I can modify the port?

**Comment by thelindat** [comment]
Right now you'll have to download and build from the source, otherwise wait for the next released build.

**Comment by FilipeQ** [comment]
Do you know when the next release will be created?

**Comment by dunak-debug** [comment]
https://github.com/overextended/oxmysql/releases/tag/v1.4.1

**Comment by FilipeQ** [comment]
The build 1.4.1 created by you is not an production build. 
I think you need to compile it and bundle the code or i'm wrong?
