### ISSUE TITLE
Undefined parameters when sending nil values from Lua

### ISSUE THREAD

**Issue by instigate77** [overextended/oxmysql#30]
when a variable in LIA has value of nil the sql query throws an error

In this example garage is nil   It comes from the DB select as NULL in the table which is the default value
But when it is inserted back it seems to ignore it and causes the undefined object.

[      script:oxmysql] [ERROR] qb-garages was unable to execute a query!
[      script:oxmysql]         Undefined object parameter #2
[      script:oxmysql]         UPDATE player_vehicles SET state = ?, garage = ?, depotprice = ? WHERE plate = ? {"1":0,"3":0,"4":"3TL036RH"}

Is there a way to have it recognize nil value and insert them as NULL?

**Comment by instigate77** [comment]
Seems like the parser sees a null parameter as undefined and throws the error above.
Maybe handle it with this mode? and check if a Lua string is null  and change it to '' then insert it back and it will be NULL?

**SET sql_mode=EMPTY_STRING_IS_NULL;**
SELECT '' IS NULL; -- returns TRUE
INSERT INTO t1 VALUES (''); -- inserts NULL

**Comment by darksaid98** [comment]
First, no. When using the `?` placeholders in a query you can not pass `nil` in Lua or `undefined` in Js as parameters. 

Dunak has expressed intent to allow passing `nil` from Lua (`undefined` from Js) that will be interpreted as `NULL`. However, it is my understanding that this will only be possible with named parameters. 

This is because using `?` placeholders accepts an ordered array. Inserting `nil` into an array does nothing since it can't store _nothing_.

**Comment by thelindat** [comment]
I tested sending nil values through `?` but it always resulted in the first value sending as `NULL` and offsetting the other parameters; worked fine with named placeholders though. I'm not good enough with JS so Dunak would have to look into it.

**Comment by nerohiro** [comment]
I am also having an issue similar to this, not sure if I should open a new issue or just post in this one. getting reports in the fxserver log like this:

[      script:oxmysql] Error: Undefined parameter cid
[      script:oxmysql]     at @oxmysql/oxmysql.js:1:326557
[      script:oxmysql]     at _ (@oxmysql/oxmysql.js:1:326629)
[      script:oxmysql]     at s._resolveNamedPlaceholders (@oxmysql/oxmysql.js:1:113372)
[      script:oxmysql]     at s.query (@oxmysql/oxmysql.js:1:113501)
[      script:oxmysql]     at @oxmysql/oxmysql.js:1:312976
[      script:oxmysql]     at @oxmysql/oxmysql.js:1:311499
[      script:oxmysql]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[      script:oxmysql]     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:62:3)
[      script:oxmysql]     at citizen:/scripting/v8/timer.js:227:32

there is a lot of cases where i use a parameter as cid as its the character identifier, but it doesn't state where the error comes from, if possible it would be nice if it could at least say where it's coming from so I can fix it. cheers.

**Comment by dunak-debug** [comment]
Use latest version and you will see error

**Comment by darksaid98** [comment]
> > Use latest version and you will see error
> 
> These errors started on latest 1.4.1 , had never seen them before then. I'm already on latest version.

Like stated before, a *fix*/*change* to this is being worked on.

**Comment by nerohiro** [comment]
my bad I misunderstood what he said, thought he was implying to use latest to see where the error was coming from. i understand now

**Comment by thelindat** [comment]
I have this mostly working at the moment for named and unnamed parameters.

**Comment by thelindat** [comment]
Only situation that fails is when sending _only_ nil _named_ parameters

**Comment by darksaid98** [comment]
Fixed in #51.
