### ISSUE TITLE
Error calling system tick function in resource oxmysql: Error: Undefined parameter fivem

### ISSUE THREAD

**Issue by chaixshot** [overextended/oxmysql#32]
```local steamid = "none"
local license = "none"
local discord = "none"
local xbl = "none"
local live = "none"
local fivem = "none"
for k,v in pairs(GetPlayerIdentifiers(_source)) do
  if string.sub(v, 1, string.len("steam:")) == "steam:" then
	  steamid = v
  elseif string.sub(v, 1, string.len("license:")) == "license:" then
	  license = v
  elseif string.sub(v, 1, string.len("xbl:")) == "xbl:" then
	  xbl  = v
  elseif string.sub(v, 1, string.len("discord:")) == "discord:" then
	  discord = v
  elseif string.sub(v, 1, string.len("live:")) == "live:" then
	  live = v
  elseif string.sub(v, 1, string.len("fivem:")) == "fivem:" then
	  fivem = v
  end
end

local discord_data = MySQL.Sync.fetchAll('SELECT * FROM `discord` WHERE `identifier` = @identifier AND (discord = @license OR discord = @discord OR discord = @xbl OR discord = @live OR discord = @fivem)', {
	['@identifier'] = steamid,
	['@license'] = license,
	['@discord'] = discord,
	['@xbl'] = xbl,
	['@live'] = live,
	['@fivem'] = fivem,
})
```

[  script:oxmysql] Error calling system tick function in resource oxmysql: Error: Undefined parameter fivem
[  script:oxmysql] stack:
[  script:oxmysql] Error: Undefined parameter fivem
[  script:oxmysql]     at @oxmysql/oxmysql.js:5758:67
[  script:oxmysql]     at _ (@oxmysql/oxmysql.js:5762:30)
[  script:oxmysql]     at s._resolveNamedPlaceholders (@oxmysql/oxmysql.js:3373:64)
[  script:oxmysql]     at s.query (@oxmysql/oxmysql.js:3378:103)
[  script:oxmysql]     at @oxmysql/oxmysql.js:5188:35
[  script:oxmysql]     at @oxmysql/oxmysql.js:5161:146
[  script:oxmysql]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[  script:oxmysql]     at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:62:3)
[  script:oxmysql]     at citizen:/scripting/v8/timer.js:227:32

**Comment by darksaid98** [comment]
Firstly the code you supplied is for MySQL-Async but I'll assume you are running some compatibility thing though.

This looks like it's the same problem as experienced & explained in #30. As explained there a change is being worked on which will make your query run fine.
