### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by Spykespy** [overextended/oxmysql#33]
Hello,

Three days ago, we've switched to oxmysql from mysql-async. It's all been running great, except for one issue. At peak times, we often get the following error:

```[  c-scripting-v8node] Error: V8 error at Reached heap limit: Allocation failed - JavaScript heap out of memory```

This error appears to come out of nowhere. After this error, the fxserver just hard-resets and boots up again. We are running the esx legacy framework, and we're seeing somewhere around 250 players at peak time. OxMySQL is the only resource running v8. I'm not much of a Javascript developer myself, so I turned to your discord for help, and they also thought this issue could be caused by oxmysql, but could not help me with the solution. They did advise me to make an issue on your git, so here I am.

If you need any more information I will respond asap! <3

**Comment by darksaid98** [comment]
A few questions for starters ^_^, 

1. What version of oxmysql are you using? (Make sure you are using the latest release)
2. FiveM Server artifact?

Do you have a lot of/or any queries where you do string concatenation ie (`'Some string ' .. variable .. ' more string'`)?

You should **NEVER** do this since the unique concatenated query will be cached. Instead use unnamed placeholders `?` or named placeholders `:parameternamehere`. See docs for [info](https://overextended.github.io/oxmysql/) regarding this.

**Comment by Spykespy** [comment]
Hi! Thanks for the response.

We are indeed using the latest version of oxmysql. Our server build is 4550.

Your point of concatenation makes a lot of sense! I can see how that would clog up the cache with unnecessary data. I will look in to this, and I'll reply with the result. 

I got this advise in your Discord as well, and I temporarily removed a resource that does this in it's queries. This did help, the server crashed after 2 hours instead of 1. I think you're on the right track.

I'll let you know how it went. But still, if this is the issue, it's weird that it would hard reset the entire server. But I'll hope for the best.

**Comment by Spykespy** [comment]
Update:

Removed all concatenation from the queries, and still crashesh with the memory error. I noticed it only happens at high player counts (180+). Any other ideas?

**Comment by dunak-debug** [comment]
Firstlz I would suggest you updating server artifacts. 4500 is far away from recommended and there was many updates to V8 runtime in the latest builds.

**Comment by dunak-debug** [comment]
Can you try dropping back to recommended 4394 ? I think it should be before node v16 update

**Comment by Spykespy** [comment]
Hi,

This didn't help. We dropped back to async and everything is back to normal. We'll keep using async I guess. I would suggest looking for memory leaks, but I guess you've ready done this before releasing. If you need any more data, let me know.

**Comment by thelindat** [comment]
Anymore information on this - is it still occurring on recent releases? @Spykespy

**Comment by thelindat** [comment]
Closing, you can request it be re-opened if anything comes up.

**Comment by benzon** [comment]
Hey,

Im actually having this issue now, it's very on/off when it happens or if it happens, so it's darn hard to pin point.
