### ISSUE TITLE
oxmysql wont connect to database sending citizen error 

### ISSUE THREAD

**Issue by migogang2x** [overextended/oxmysql#34]
so i updated my server did it local host first . local host works connects to database, when i upload the server via vps its crashing on alot of errors on things that i did not touch 

[ script:ghmattimysql] [ghmattimysql] [SUCCESS] Database server connection established.

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-drugs/server/deliveries.lua:210)

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-lapraces/server/main.lua:7)

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-houses/server/main.lua:3)

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-banking/server/main.lua:8)

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-core/server/main.lua:21)

[ script:qb-methlab] Lab entry has been set to location: 1

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-spawn/server.lua:3)

[ svadhesive] Server license key authentication succeeded. Welcome!

[ script:oxmysql] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:1155: No such export fetch in resource oxmysql

[ script:oxmysql] &gt; fn (@qb-weed/server/main.lua:39)

my database password string is set up correctly i dont understand why it would'nt work its crashing lapraces and i did not touch that banking i didnt touch , what is going on ?

**Comment by dunak-debug** [comment]
Are you sure you downloaded release and not source code?

**Comment by migogang2x** [comment]
yes i did i downloaded both nun are working for me on zap-hosting

**Comment by dunak-debug** [comment]
Show me your oxmysql folder and mysql configuration

**Comment by migogang2x** [comment]
so every time you change your connection string with zap hosting it changes it back to what they want it ass you have to goto settings and turn database configuration off and it lets you but the correct oxmysql string in place and save it "mysql://user:password@host/database?charset=utf8mb4&dateStrings=true"

**Comment by migogang2x** [comment]
fixed it
