### ISSUE TITLE
Unable to execute a query!

### ISSUE THREAD

**Issue by requestrip** [overextended/oxmysql#38]
When i have more than 2 parameter script is  unable to execute a query.
When i have 2 any of these paremeters it's work for example 'identifier', 'owner', or 'firstowner', 'co_owner1',
![image](https://user-images.githubusercontent.com/80534501/136384343-53bcab34-7388-41e4-ad5d-9bd4c142285e.png)
![image](https://user-images.githubusercontent.com/80534501/136384397-9143ebd9-3958-4e7e-a80f-6cd29b22538a.png)

**Comment by thelindat** [comment]
Why are you sending more parameters than it takes? The real error here is that we don't throw an error when sending more params than placeholders.

You need `OR COLUMN_NAME = ?` for each column name you're trying to send... or just rename your weird columns.

**Comment by dunak-debug** [comment]
If you have mysql-async it doesnt mean your query is not bad. Its just that mysql-async doesnt show you  the error
