### ISSUE TITLE
 Error calling system tick function in resource oxmysql: Error: Undefined parameter fivem

### ISSUE THREAD

**Issue by requestrip** [overextended/oxmysql#39]
When player connecting script shows that error and player can't load 
I`m using oxmysql 1.5.0 from Releases
System: Linux FXServer 4478
![image](https://user-images.githubusercontent.com/80534501/136437385-da551039-c33d-4f1e-97bb-6a06b961684f.png)

**Comment by thelindat** [comment]
You have an undefined parameter in a query somewhere - you cannot as of yet pass nil values.
