### ISSUE TITLE
Debug enhancement

### ISSUE THREAD

**Issue by BaziForYou** [overextended/oxmysql#44]
add debug in file console or both config and debug level
like these

set mysql_log_level 8
set mysql_debug "File"
set mysql_log_file_format "debug-mysql.log"

![image](https://user-images.githubusercontent.com/20565441/132961195-85cdcb23-fb31-4da1-a9de-fb2d9796dfd5.png)
![image](https://user-images.githubusercontent.com/20565441/132961233-4f2daf5d-f56e-478a-ac43-004a8a8579f5.png)
![image](https://user-images.githubusercontent.com/20565441/132961193-f1c05be1-b2f0-40b2-850a-e4090204b359.png)

**Comment by dunak-debug** [comment]
#72
