### ISSUE TITLE
I can't run more than one query in an .execute?

### ISSUE THREAD

**Issue by Wezli** [overextended/oxmysql#45]
Example:
in oxmysql
"INSERT INTO users(whitelisted, banned) VALUES(false, false); SELECT LAST_INSERT_ID() AS id;"
or multiple "CREATE TABLE IF NOT EXISTS" in the same query string
It just doesn't run, but on others like mysql-async and ghmattimysql the query runs without problems/errors

**Comment by dunak-debug** [comment]
If you want to return insert id just use https://overextended.github.io/oxmysql/insert.html
