### ISSUE TITLE
Fatal Error in HandleScope::HandleScope

### ISSUE THREAD

**Issue by XenoS-ITA** [overextended/oxmysql#5]
i saw the post in the FiveM forum and I decided to try it, I downloaded the build, I started it, I set the server.cfg and after I tried to do a simple select and the server crashed with this error, I don't know if I did something wrong but I couldn't test it
![immagine_2021-09-10_222829](https://user-images.githubusercontent.com/55803068/132913937-9b97721d-3476-4ec5-ac77-4b245b53a6b6.png)

My connection string: `mysql://root@localhost/utility?charset=utf8mb4`

**Comment by Korioz** [comment]
Try updating your fxserver artifacts

**Comment by XenoS-ITA** [comment]
@Korioz I updated to the last artifacts and now works, thanks for the tip.

**Do you have this problem too?**
My solution was: **update the artifacts** (i updated them to **4394**)
