### ISSUE TITLE
Was unable to execute a query

### ISSUE THREAD

**Issue by Slypher** [overextended/oxmysql#57]
Hey, guys!
I'm having trouble building a query that automatically creates the database, I did a test with ghmattimysql (node ​​version) and managed to create the database successfully.

## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Screenshots**
![errorPrint](https://cdn.discordapp.com/attachments/892015434835062814/901311643894579231/unknown.png)

**Code**
```lua

local connectionString = GetConvar('mysql_connection_string', '')

if connectionString:find('mysql://') then

      local databaseName = connectionString:match('[^/][%w]*[?$]'):sub(0, -2)

      exports['executeSync']:execute(('CREATE DATABASE IF NOT EXISTS %s'):format(databaseName))

end

```

**Expected behavior**
Create database

**Server details**
- FX Server artifact: 4821
- Operating system: Windows 11
- Framework: Custom

**Comment by dunak-debug** [comment]
Thats because wrapper expects existing database when establishing connection. I will try to make it not required so you can select database at run time.

**Comment by thelindat** [comment]
This will be patched next update by modifying the default connection flags.

**Comment by thelindat** [comment]
@Slypher @Tinky124
Database is no longer required by the connection string as of v1.8.0

**Comment by mrsmit00001** [comment]
[      script:oxmysql] Error: ethicalpixel-adminmenu was unable to execute a query!
[      script:oxmysql] Query: SELECT * FROM ethicalpixel_admin_banned WHERE license = ?
[      script:oxmysql] ["license:3dc6f42f0d75e4b8104486b5cdb3fc997abb418e"]
[      script:oxmysql] Table 'qbcoreframework_5881c7.ethicalpixel_admin_banned' doesn't exist
