### ISSUE TITLE
Failed to execute simple SELECT

### ISSUE THREAD

**Issue by SeaLife** [overextended/oxmysql#60]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
So my addon fetches all vehicles owned by non-citizens periodic with:

```
Citizen.CreateThread(function()
    while true do
        MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE job != @job', {job = 'citizen'}, function(data)
            VehicleTable = {}
            for k, v in pairs(data) do -- this is line 53 in sealife_society/server/main.lua
                VehicleTable[v.plate] = v
            end
        end)

        Citizen.Wait(60000)
    end
end)
```

I recently updated to the latest version and im now getting this error message, i normally know what to do in this case, but  the query just worked fine in a older version:

```
[      script:oxmysql] 
[      script:oxmysql] [ERROR] sealife_society was unable to execute a query!
[      script:oxmysql]         You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'TRANSACTIONed_vehi\0012' at line 1
[      script:oxmysql]         SELECT * FROM owned_vehicles WHERE job != 'citizen'
[script:sealife_socie] SCRIPT ERROR: @sealife_society/server/main.lua:53: bad argument #1 to 'for iterator' (table expected, got nil)
[script:sealife_socie] &gt; ref (@sealife_society/server/main.lua:53)
```

**Code**

See above

**Expected behavior**

A array returning containing all the data :D

**Server details**
FX Server: 4517
OS: Ubuntu 20 LTS
Framework: ESX ?

**Comment by dunak-debug** [comment]
No problem just anything that is able to reproduce this issue, don´t forget SQL and also some info about database setup (mariadb/mysql, version). Also just to be sure, can you try also updating your artifacts to latest one (4889 atm - it has nothing to do with it but you know give it a try cause this is very strange issue)

**Comment by SeaLife** [comment]
We are on 4517 on our Test Server, yeah, i will update this instance to the latest version :)

We use MariaDB on the latest tag with docker

**Comment by dunak-debug** [comment]
Ahh, ok then. So send me reproducible resource with sql

**Comment by SeaLife** [comment]
Hey,

i've changed the code to
```lua
Citizen.CreateThread(function()
    while true do
        exports.oxmysql:execute('SELECT `plate`, `owner`, `job` FROM owned_vehicles WHERE `job` != ?', {'citizen'}, function(data)
            VehicleTable = {}
            for k, v in pairs(data) do
                VehicleTable[v.plate] = v
            end
        end)

        Citizen.Wait(60000)
    end
end)
```
(using the export directly instead of the wrapper)

The issue dissappeard ..

Maybe this problem be related to the wrapper?

**Comment by thelindat** [comment]
> ```lua
> Citizen.CreateThread(function()
>     while true do
>         exports.oxmysql:execute('SELECT `plate`, `owner`, `job` FROM owned_vehicles WHERE `job` != ?', {'citizen'}, function(data)
>             VehicleTable = {}
>             for k, v in pairs(data) do
>                 VehicleTable[v.plate] = v
>             end
>         end)
> 
>         Citizen.Wait(60000)
>     end
> end)
> ```
> Its probably due to executing many statements at once? I dont know anymore.. I cant reproduce it in a simple script either

You say you're executing many statements at once, but this is just one so what do you mean? Anyway you may see some benefits by utilising the prepare function instead.

```lua
Citizen.CreateThread(function()
    while true do
        exports.oxmysql:prepare('SELECT `plate`, `owner`, `job` FROM owned_vehicles WHERE `job` != ?', {{'citizen'}}, function(data)
            VehicleTable = {}
            for k, v in pairs(data) do
                VehicleTable[v.plate] = v
            end
        end)

        Citizen.Wait(60000)
    end
end)
```

I will just throw out here, though; there's very little point in performing this query every single minute - what are you trying to accomplish? How many vehicles are being stored in that table, and is it absolutely necessary to do so rather than just querying the database when you need the information?

Most ESX resources have the terrible habit of loading an entire database into tables, sometimes storing them in xPlayer as well; it's not an efficient use of memory (especially if you're not utilising Lua 5.4 with the improved garbage collection).

**Comment by SeaLife** [comment]
We'r using Lua 5.4 everywhere in every resource we are creating.

As i edited my post above:
> I changed the Citizen.Wait to 54530ms and the error is gone even after a restart... Maybe a thread-safety problem?

I also increased the PID limit and had no issues at all after those changes....

**Comment by SeaLife** [comment]
We switched over to Windows Server 2022 this night and we still get this TRANSACTION issue 
![image](https://user-images.githubusercontent.com/6567620/144013119-96c88f0a-a87f-461e-806e-6b9b9193e27b.png)

I dont know what tf is happening exactly, but it seems to be a problem which occurs if many requests are triggered concurrently? But i dont know exactly

**Comment by darksaid98** [comment]
> We switched over to Windows Server 2022 this night and we still get this TRANSACTION issue ![image](https://user-images.githubusercontent.com/6567620/144013119-96c88f0a-a87f-461e-806e-6b9b9193e27b.png)
> 
> I dont know what tf is happening exactly, but it seems to be a problem which occurs if many requests are triggered concurrently? But i dont know exactly

Dunak asked 29 days ago for a resource and DB setup with which this error can be reproduced. You also mentioned you use latest tag for MariaDB on docker which is somewhat unspecific. (SQL Server version can be found mid-bottom in the HeidiSQL client if you use that).

We could sit around and create interesting hypotheses as to why this is happening, can't do much more without repro and DB setup.

**Comment by thelindat** [comment]
Closing this for now. If you provide more information and a repro for us we can open it back up.
