### ISSUE TITLE
i get this type error in the server console using 1.7.0

### ISSUE THREAD

**Issue by Dankbudbaker** [overextended/oxmysql#61]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [X] I am using the latest release
- [X] I have referenced previously reported issues
- [X] I have referenced available documentation and cannot resolve the issue
- [X]  I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
this is the error i get in the server console

[      script:oxmysql] Database server connection established!
[      script:oxmysql] Uncaught TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[      script:oxmysql] node:internal/errors(464,5): __node_internal_captureLargerStackTrace
[      script:oxmysql] node:internal/errors(371,5): NodeError
[      script:oxmysql] node:buffer(322,9): from
[      script:oxmysql] @oxmysql/oxmysql.js(1,311927): t.encode
[      script:oxmysql] @oxmysql/oxmysql.js(1,304656): toPacket
[      script:oxmysql] @oxmysql/oxmysql.js(1,98097): start
[      script:oxmysql] @oxmysql/oxmysql.js(1,92161): execute
[      script:oxmysql] @oxmysql/oxmysql.js(1,112506): handlePacket
[      script:oxmysql] @oxmysql/oxmysql.js(1,112628): handlePacket
[      script:oxmysql] @oxmysql/oxmysql.js(1,107273):
[      script:oxmysql]
[      script:oxmysql] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[      script:oxmysql] Uncaught TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[      script:oxmysql] node:internal/errors(464,5): __node_internal_captureLargerStackTrace
[      script:oxmysql] node:internal/errors(371,5): NodeError
[      script:oxmysql] node:buffer(322,9): from
[      script:oxmysql] @oxmysql/oxmysql.js(1,311927): t.encode
[      script:oxmysql] @oxmysql/oxmysql.js(1,304656): toPacket
[      script:oxmysql] @oxmysql/oxmysql.js(1,98097): start
[      script:oxmysql] @oxmysql/oxmysql.js(1,92161): execute
[      script:oxmysql] @oxmysql/oxmysql.js(1,112506): handlePacket
[      script:oxmysql] @oxmysql/oxmysql.js(1,112628): handlePacket
[      script:oxmysql] @oxmysql/oxmysql.js(1,107273):
[      script:oxmysql]
[      script:oxmysql] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

**Server details**
- FX Server artifact - 3846
- Operating system - windows
- Framework - qb-core framework

**Comment by darksaid98** [comment]
You forgot to put a colon in `exports.oxmysql:execute`. `oxmysql:execute` not `oxmysql.execute` etc.

**Comment by Dankbudbaker** [comment]
thank you! that was the problem, there was one i would have never found

**Comment by dunak-debug** [comment]
Thats rather Lua syntax issue than oxmysql if you want to know. Exports in LUA are consisted of metatable and to call metatable functions you must use : because metatable uses self as first parameter. So for every export you have to use :.
