### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by ShadowOfVoid** [overextended/oxmysql#62]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x ] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [ x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
```lua
[ERROR] test was unable to execute a query!
[      script:oxmysql]         read ECONNRESET
[      script:oxmysql]         UPDATE users SET rp_xp = ?, rp_rank = ? WHERE identifier = ? [689500,7,"char1:steam:00000"]
[      script:oxmysql] Trace: Error: read ECONNRESET
[      script:oxmysql]     at PromisePool.query (@oxmysql/oxmysql.js:17259:38)
[      script:oxmysql]     at execute (@oxmysql/oxmysql.js:20125:58)
[      script:oxmysql]     at Object.callback (@oxmysql/oxmysql.js:20341:13)
[      script:oxmysql]     at citizen:/scripting/v8/main.js:156:41
[      script:oxmysql]     at Number.__cfx_wrap_588 (citizen:/scripting/v8/main.js:24:12)
[      script:oxmysql]     at citizen:/scripting/v8/main.js:30:16
[      script:oxmysql]     at citizen:/scripting/v8/main.js:155:11
[      script:oxmysql]     at Console.trace (citizen:/scripting/v8/console.js:297:19)
[      script:oxmysql]     at execute (@oxmysql/oxmysql.js:20140:34)
[      script:oxmysql]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Code**
```lua
exports.oxmysql:update('UPDATE users SET rp_xp = ?, rp_rank = ? WHERE identifier = ?', {
            goalXP,
            goalRank,
            xPlayer.identifier
        }, function(result)

        end)
```

**Additional context**
well , sometimes this and only this query get this error ! but mostly it will executed without any errors , so based on some searches i guess i have to increase the wait timout for mysql ? but why this happens for only this query ? on a table that contains like 5 row max ! ( test server )

example log of same query executing without an error

```lua
[      script:oxmysql] [DEBUG] test took 0ms to execute a query!
[      script:oxmysql]         UPDATE users SET rp_xp = ?, rp_rank = ? WHERE identifier = ? [966000,10,"char1:steam:00000"]
```

**Server details**
- FX Server artifact = 4920
- Operating system = win 10
- Framework = extended

**Comment by dunak-debug** [comment]
>"ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more application protocol errors. You could look at the API server logs to see if it complains about something.

> What could also be the case: at random times, the other side is **overloaded** and simply kills the connection as a result. If that's the case, depends on what you're connecting to exactly…

https://stackoverflow.com/questions/17245881/how-do-i-debug-error-econnreset-in-node-js

**Comment by dunak-debug** [comment]
Your dedicated server parameters?

**Comment by dunak-debug** [comment]
Closing - no response yet
