### ISSUE TITLE
Production Problem with thread_monitor Resource temporarily unavailable in pthread_create

### ISSUE THREAD

**Issue by SeaLife** [overextended/oxmysql#63]
## Issue checklist

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

We moved oxmysql on our production server (FXServer 4960) and the server instantly crash if a player connects with the following error:

```
thread_monitor Resource temporarily unavailable in pthread_create
thread_monitor Resource temporarily unavailable in pthread_create
thread_monitor Resource temporarily unavailable in pthread_create
thread_monitor Resource temporarily unavailable in pthread_create
thread_monitor Resource temporarily unavailable in pthread_create
thread_monitor Resource temporarily unavailable in pthread_create
> quit "Server Restart (Crash erkannt)."
```

As far as i can see, the MySQL stuff works just fine, all addons can fetch their data and stuff, but as soon as a user connects, the server crashes.

We used mysql-async with a explicit utf8mb4 charset just to let you know. But i was not able to set this parameter with oxmysql as the connection string did not allow the ?... paremeter stuff like mysql-async did.

oxmysql is actually running on our test server which is FXServer 4879

**Code**

None

**Expected behavior**

No crash?

**Server details**
- FXServer 4960
- Ubuntu 20.04 LTS up-to-date
- ESX

**Comment by thelindat** [comment]
> But i was not able to set this parameter with oxmysql as the connection string did not allow the ?... paremeter stuff like mysql-async did.

```lua
set mysql_connection_string "mysql://root:12345@localhost/es_extended?charset=utf8mb4"
set mysql_connection_string "user=root;database=es_extended;password=12345;charset=utf8mb4"
```
Either connection string works and accepts parameters, with more available at [pool.d.ts](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/Pool.d.ts#L10) and [connection.d.ts](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/Connection.d.ts#L8).

Others have been able to run the resource fine on Linux and in Docker; I know there have been memory issues on your server going back a while which may be related to this error but I don't know much about these matters. I still don't understand the other issue you've been having with queries getting bastardised with random text..


Are you able to test the server running on Windows and reproduce these issues?

**Comment by SeaLife** [comment]
Hey, thanks for that, we'll try that on our next maintenance window.

We have switched to a dedicated sever lately and we hope to fix those issues ASAP.

I'll close this ticket and re-open it if the charset did not fix the problem. :)

**Comment by SeaLife** [comment]
The problem seems to be docker related, probably related to pterodactyl's setting on starting the container.

Running "bare-metal" as root with `./run.sh` worked. I increased the maximum PID's in the container settings and hope for a better result. Maybe the system hit the 256-PID limit which was enforced by pterodactyl.

I'll get in touch with the developers at pterodactyl and ask them how to remove any "limitations" their are enforcing to ensure my problems are not docker/pterodactyl related.

**Comment by thelindat** [comment]
There was a fix pushed for the mysql2 package which resolves an issue with readField and textParser, though it was reported with excessively large returns; not that it's impossible for there to have been some benefits here.

A somewhat recently change to typecasting has resulted in a few problems, so if you're performing queries frequently enough you can try utilising the prepare export (reference [this function](https://github.com/overextended/es_extended/blob/main/server/functions.lua#L171-L196)). I'll expand on this further in #60.
