### ISSUE TITLE
Error loading script oxmysql.js

### ISSUE THREAD

**Issue by Cuubyke** [overextended/oxmysql#64]
- [x] I am using the latest release
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Error loading script oxmysql.js

**Screenshots**
![image](https://user-images.githubusercontent.com/79209629/141969167-923e8a72-1a97-430c-bac9-119c8bf8d5df.png)

**Server details**
- FX Server artifact: latest
- Operating system: Debian 10
- Framework Qbus

**Comment by dunak-debug** [comment]
Read documentation and set up connection string correctly

**Comment by dunak-debug** [comment]
Maybe I was wrong. I got another report with no scheme found error.

Maybe https://github.com/overextended/oxmysql/commit/b004ec943dcf45b8886c491ac907c07998110a95 broke something? @thelindat

**Comment by dunak-debug** [comment]
Anyway connection string using semicolon format is deprecated in oxmysql. Use new url syntax

`mysql://user:passsword@host/database`

**Comment by thelindat** [comment]
> 
> 
> Maybe I was wrong. I got another report with no scheme found error.
> 
> Maybe [b004ec9](https://github.com/overextended/oxmysql/commit/b004ec943dcf45b8886c491ac907c07998110a95) broke something? @thelindat

We were using `database=` to check if string was using comma values, but I changed it to check for host due to people wanting to connect without a database.

**Comment by Cuubyke** [comment]
> Anyway connection string using semicolon format is deprecated in oxmysql. Use new url syntax
> 
> `mysql://user:passsword@host/database`

This worked for me now dont know how :)

**Comment by dunak-debug** [comment]
> > Maybe I was wrong. I got another report with no scheme found error.
> > Maybe [b004ec9](https://github.com/overextended/oxmysql/commit/b004ec943dcf45b8886c491ac907c07998110a95) broke something? @thelindat
> 
> We were using `database=` to check if string was using comma values, but I changed it to check for host due to people wanting to connect without a database.

Maybe try setting up regex for checking `;` and `=` we will see or maybe get rid of it at all in 2.0
