### ISSUE TITLE
Incorrect date passing from JS (Compiled TS) to Lua

### ISSUE THREAD

**Issue by napei** [overextended/oxmysql#67]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x ] I am using the latest release
- [ x ] I have referenced previously reported issues
- [ x ] I have referenced available documentation and cannot resolve the issue
- [ x ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
When executing the following statement in a JS server resource (compiled from TS), the resulting `Date()` value does not appear correctly in the query, or the Lua handler for `oxmysql` causing it to fail.

```ts
    const event: XPEvent = {
      citizenid: citizenID,
      category_id: categoryID,
      value,
      time: new Date(),
    };

    await global.exports.oxmysql.insertSync(`INSERT INTO xp_events SET ?;`, [
      event,
    ]);
```

**Screenshots**

I receive the following error on the server.
![image](https://user-images.githubusercontent.com/8946502/142095335-c7fb8593-34d1-4681-9d14-061a24ca6924.png)
Note the extra messages from oxmysql. I have added a print statement to `wrapper.lua` as follows
![image](https://user-images.githubusercontent.com/8946502/142095419-bf805991-abb4-43c5-aa29-87ffd6253bd3.png)

I've also added `console.log()` statements to `oxmysql.js` in the relevant `insertSync` export, however they never get executed, which is interesting.

You can see from the prints, that once the data hits Lua the Date object is lost (`"time":[]`) and that the query value is empty, throwing the error.
```
`time` = ,
```
The `time` column is a `TIMESTAMP` column in MariaDB.

**Expected behavior**
Date objects should be able to be passed through, or a workaround should be documented.

**Additional context**
I checked documentation, and documentation for `node-mysql2` and couldn't find anything helpful (I might have missed something). I think that it's more than likely a problem with how CFX passes data through from JS to Lua and more than likely it will need to be wrapped and converted to a string or something on my resource's side. I'm not an expert either, but I find it odd that my JS resource isn't calling the JS exports inside `oxmysql` and it's instead calling Lua functions.

**Server details**
- FX Server artifact: `4973`
- Operating system: `Windows 11`
- Framework: `QBCore` *(irrelevant I think, this is a custom resource)*

**Comment by dunak-debug** [comment]
This is not an issue with oxmysql neither cfx. FiveM msgpack does serialize only basic types and that doesnt include Date class. How would it define js Date in other scrt? You can not even pass date trough events also. If you want to insert current date use sql date functions. For example "NOW()"

**Comment by dunak-debug** [comment]
Or define column as timestamp and pass "Date.now()" which returns timestamp number

**Comment by thelindat** [comment]
> I've also added console.log() statements to oxmysql.js in the relevant insertSync export, however they never get executed, which is interesting.

Remove the wrapper from fxmanifest to utilise the JS exports; these aren't default because the recommended server build hasn't been updated in nearly 3 months and does not support async return values when using JS.

**Comment by napei** [comment]
Thanks for the responses @dunak-debug & @thelindat 

> This is not an issue with oxmysql neither cfx. FiveM msgpack does serialize only basic types and that doesnt include Date class.

I suspected as much. I'm not too concerned honestly, I just hoped there would be a nicer way to do it that isn't hacky. Perhaps this should be opened/reported in [citizenfx/fivem](https://github.com/citizenfx/fivem)? Could this also be added to the documentation for `oxmysql` just as a disclaimer?

> If you want to insert current date use sql date functions. For example "NOW()"

And if I want to pass through an arbritrary time that is calculated client/server side which isn't the current time, instead of relying on SQL? I suppose I could just use UNIX timestamps or formatted strings in that case and MySQL/MariaDB/etc. can parse it accordingly.

**Comment by dunak-debug** [comment]
This is not an issue for cfx either. As I said how would you introduce javascript Date object in Lua and C#? Event serialization can handle only basic types like string integer boolean.

**Comment by dunak-debug** [comment]
Work with dates as timestamps (integer) not classes/objects

**Comment by napei** [comment]
> This is not an issue for cfx either. As I said how would you introduce javascript Date object in Lua and C#? Event serialization can handle only basic types like string integer boolean.

JS `Date()` serialises nicely to a string when using JSON. Representing a javascript date object in Lua and C# is as easy as using the build in date/time classes. It doesn't have to function the same with class methods etc, the function of using `Date()` as a data property is to signify its value.

> Work with dates as timestamps (integer) not classes/objects. You can always parse string as timestamp and vice versa.

This is probably the option to go with then.

**Comment by dunak-debug** [comment]
Of course there is way but cfx utilises msgpack not json. You could utilise new extension in msgpack that will deserialize object as Date object but its unnecessary. Like you saw its just easy to parse dates from timestamp and opposite get timestamp from date object. That way you just send number over event means also less data sent over

**Comment by dunak-debug** [comment]
oxmysql also because of msgpack returns dates from database as timestamts not date object so it can be handled in all script runtimes.

**Comment by napei** [comment]
> Of course there is way but cfx utilises msgpack not json. You could utilise new extension in msgpack that will deserialize object as Date object but its unnecessary. Like you saw its just easy to parse dates from timestamp and opposite get timestamp from date object. That way you just send number over event means also less data sent over

Yeah makes sense. I'll just stick to strings then. Thanks :)

**Comment by napei** [comment]
> > I've also added console.log() statements to oxmysql.js in the relevant insertSync export, however they never get executed, which is interesting.
> 
> Remove the wrapper from fxmanifest to utilise the JS exports; these aren't default because the recommended server build hasn't been updated in nearly 3 months and does not support async return values when using JS.

Do you know which version this is supported from?

**Comment by dunak-debug** [comment]
https://github.com/citizenfx/fivem/commit/9a69eeebd7b621af4ff3c8bc25977a81038dd80a

Should be from 4504. I can recommend using newer because node got update to v16 from v12 not sure which commit you can lookup

**Comment by napei** [comment]
> [citizenfx/fivem@9a69eee](https://github.com/citizenfx/fivem/commit/9a69eeebd7b621af4ff3c8bc25977a81038dd80a)
> 
> Should be from 4504. I can recommend using newer because node got update to v16 from v12 not sure which commit you can lookup

Yeah that's fine then. Running 4947 in production so that's no problem. Very much enjoying node 16 support
