### ISSUE TITLE
Option to connect to multiple databases

### ISSUE THREAD

**Issue by StanvanderPloeg** [overextended/oxmysql#68]
For our current project we use two different databases, currently (so far I can tell/see) it's not possible to connect to two different databases without changing the source code of the project. 

Is it possible to implement a way to 'select' the database you would like to connect to?

- Example:
(DB1 : CAD)
(DB2 : Ingame)

Both have different values in them, one is most concerned about the CAD resource while the other one supports different information for different resources. 
My 'need' / idea is to be able to connect to the CAD Database at line 16 of the code and use the ingame DB at line 53 in the code

(lines are examples)

If more information is required, or anything might be unclear feel free to contact me.
_Code below is not tested_

`
wrapper.lua
---@param db int
exports('setDBConnection', function(db)
    local p = promise.new()
    oxmysql:updateConnectionString(db)
    return Citizen.Await(p)
end)
`

`
oxymsql.js
let connectionString = GetConvar('mysql_connection_string_1', '');
const updateConnectionString = async (db) => {
  /** 
   * There are a few things how you can do it here, you can either throw the connection strings in an array..
   * And then set config on how to separate the different DB.. easiest is to say give me either DB1 or DB2 from the other script side  */
 // DB gives - 1 or 2
  connectionString = GetConvar('mysql_connection_string_' + db, '');
}
`

**Comment by darksaid98** [comment]
My take on this is: While possible to make a resource or oxmysql do this. It wouldn't be practical. A resource with this functionality should be designed from the ground up with this idea in mind. 

The only sane way for something like this to be implemented (that I can think of at this time) would be pre-defined databases in a config. Followed by users passing an argument for which DB to query to when using the exports. This would break backward compatibility with other resources as well as current usages of oxmysql. That's a lot of work for a lot of people to make an unconventional (in FiveM) use case work.

The implementation you suggested would allow resources to query the wrong DB and doesn't account for the way oxmysql uses connection pools.

**Comment by thelindat** [comment]
Imagine you swap database to perform some query, then while it's processing some other query tries to run with the wrong database selected. I don't see much reason to be swapping around databases like this, you would instead require multiple connection pools to be created and new functions to decide on the pool to utilise.

This isn't something that I see being added anytime soon (if at all).

**Comment by StanvanderPloeg** [comment]
> My take on this is: While possible to make a resource or oxmysql do this. It wouldn't be practical. A resource with this functionality should be designed from the ground up with this idea in mind.
> 
> The only sane way for something like this to be implemented (that I can think of at this time) would be pre-defined databases in a config. Followed by users passing an argument for which DB to query to when using the exports. This would break backward compatibility with other resources as well as current usages of oxmysql. That's a lot of work for a lot of people to make an unconventional (in FiveM) use casework.
> 
> The implementation you suggested would allow resources to query the wrong DB and doesn't account for the way oxmysql uses connection pools.

Yeah, I figured as much. Tbh didn't expect much from it as it is indeed not a common case. It was always worth a shot at least :D 
appreciate the fast response, and I think there isn't much more to do than to work with one db
