### ISSUE TITLE
Error on http mysql connection string if contains a ,

### ISSUE THREAD

**Issue by LazaroGrosso** [overextended/oxmysql#69]
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
When using a "," on mysql_connection_string, it gives you an error

**Screenshots**

![Without a ,](https://user-images.githubusercontent.com/86653533/143732547-bc4a88c1-72c4-426b-ba20-fd6e41de2315.png)
![With ,](https://user-images.githubusercontent.com/86653533/143732548-f452ee3a-1e06-4ccd-a64d-8295f537381a.png)

**Code**

- Not needed

**Expected behavior**

- Not needed

**Additional context**

- Not needed

**Server details**
- 4394 ~ 5002
- Windows 10 ~ Windows Server
- Not relevant

**Comment by thelindat** [comment]
I've just pushed a release with the updated parser, which likely resolves it.

**Comment by darksaid98** [comment]
Is this issue fixed for you on the latest release @LazaroGrosso ?

**Comment by LazaroGrosso** [comment]
Yes sir, the issue has been resolved.
