### ISSUE TITLE
[BUG] If slow server start connection errors

### ISSUE THREAD

**Issue by benzon** [overextended/oxmysql#73]
After the changes in the latest versions.

I have a issue first time i start up my dev server daily it starts abit slow, and that results in connection errors, if i then restart the server i starts fast like normal, no issues.

So looks like it's gotten way to sensitive to slow starting servers now, not sure whats the reason behind this is.

**Comment by dunak-debug** [comment]
Specific connection error?

**Comment by benzon** [comment]
Connection timeout, so it's like it wants faster reply now then compared to earlyer.

**Comment by MercedessBenz** [comment]
![image](https://user-images.githubusercontent.com/25920716/144887691-c4e0b182-4f76-4559-9bbf-5f7c6d542bd2.png)

Yes, i have same same error, if my resources are too much making it take too long to load then database related error will appear in console

**Comment by benzon** [comment]
So the changes today gave me a new issue, Can't add new command when connection is in closed state not sure what's going on here.

**Comment by thelindat** [comment]
What do you mean you can't add a command?

**Comment by benzon** [comment]
To be honest i dont know haha.

The issue i have with 1.8.5 is connection closed, this is on a dev server with 1 player.

If i revert back to a older build i dont have this issue it looks like it was introduced in 1.8.5

Note, the SQL server in use is remote.

**Comment by thelindat** [comment]
Can you try https://github.com/overextended/oxmysql/releases/download/test/oxmysql-test.zip

**Comment by benzon** [comment]
Sure thing ill try it when i get up again

**Comment by benzon** [comment]
Looks like it works so fare, no Timeouts, or closed connections 30 min of testing done ill do 30 min more just to make sure.

**Comment by oakyydev** [comment]
I'm having the same issue as he mentioned:

```
[      script:oxmysql] [ERROR] oakyPhone was unable to execute a query!
[      script:oxmysql]         Can't add new command when connection is in closed state
[      script:oxmysql]         SELECT phone_number, firstname, lastname FROM users WHERE identifier = "XXXXXXXXXXXXXXXXXXXXXXX" []
```

**Comment by benzon** [comment]
> I'm having the same issue as he mentioned:
> 
> ```
> [      script:oxmysql] [ERROR] oakyPhone was unable to execute a query!
> [      script:oxmysql]         Can't add new command when connection is in closed state
> [      script:oxmysql]         SELECT phone_number, firstname, lastname FROM users WHERE identifier = "XXXXXXXXXXXXXXXXXXXXXXX" []
> ```

Did you try the test version @thelindat linked to i have not had issues since.

**Comment by thelindat** [comment]
Seemingly resolved.
