### ISSUE TITLE
Lua promises resolving with errors

### ISSUE THREAD

**Issue by thelindat** [overextended/oxmysql#74]
**Describe the bug**
During Citizen.Await, promises are returning an error [see scheduler.lua](https://github.com/citizenfx/fivem/blob/master/data/shared/citizen/scripting/lua/scheduler.lua#L116-L145).

> this issue is coming when the query is returning a column that has a null data in it

Awaiting more information and a simple repro.

**Screenshots**
![image](https://user-images.githubusercontent.com/65407488/144943327-9b2f90f6-fd13-4aca-9631-2939abb0aba0.png)
---

Pending information from @akassl-lab

**Code**
```lua
    -- If applicable, include the query and relevant code
```

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by akassl-lab** [comment]
The issue is not on your side. Reverted back to 4998 on linux build and everything issue just went away.

The query was a simple SELECT * FROM a user table.

So my advice to others, don't update to the latest build if you're on Linux and running oxmysql until further notice

**Comment by thelindat** [comment]
> The issue is not on your side. Reverted back to 4998 on linux build and every issue just went away.
> 
> The query was a simple SELECT * FROM a user table.
> 
> So my advice to others, don't update to the latest build if you're on Linux and running oxmysql until further notice

My linux server is currently on 5046 and has no issue, along with other ones being reported (this script error one is popular, as is this command one.
![image](https://user-images.githubusercontent.com/65407488/145099310-13be50d2-5392-45c3-bc1a-8bfc804d1ab2.png)

Could you send me the query you're running so I can try to reproduce it?

**Comment by thelindat** [comment]
Try https://github.com/overextended/oxmysql/releases/download/test/oxmysql-test.zip

**Comment by akassl-lab** [comment]
> Try https://github.com/overextended/oxmysql/releases/download/test/oxmysql-test.zip
> 
> Out of interest, are you using lib/MySQL.lua?

Yes we are and it seems that this issue is being caused by an external resource that is encrypted. The owner sent me the snippet of the code that is throwing that error.

Today we reverted back to 1.8.3 but now it seems the server is crashing every 4 hours for a "V8 error at Committing semi space failed.: Allocation failed - JavaScript heap out of memory" and I know the issue is being caused by oxmysql

I can send the crash dump if you want

**Comment by thelindat** [comment]
Unfortunately there isn't much I can do about that error. Are you running pterodactyl or some other container and able to assign more memory?

Unfortunately it's an issue that can happen with mysql-async too, but I'm not sure why it's seemingly more common here. May need to dig into node-mysql2 a bit more, and I know there are changes coming.. eventually. I want to improve logging in the future but if we're running into V8 memory issues as is, it may need to wait.

I do have some general improvements I could test with the current code (been working on parts for v2.0.0) and bring over, but it's unlikely to bring much of a change in terms of memory use. There's not really much profiling provided for the runtime by FXServer either 🤔

**Comment by akassl-lab** [comment]
The thing is that we have 128GB of Memory, the server with around 100 players is only using between 5-10GB of memory. Our server resources are very optimized but the weird thing is, even before the crash there's no major increase. We never touch 20GB+ . Nothing else is running on the dedicated server except the FXServer itself and the database.

**Comment by thelindat** [comment]
I'm not sure how much memory FXServer will use, but people have used oxmysql with over 400 players running garbage resources so it's difficult to find a cause. I can only assume a memory leak, but I'm not in a position to do in-depth analyses of V8, Node, and the script runtime.

oxmysql-test just reverts some of the changes.
- JS "sync" exports will only be enabled if you disable wrapper.lua
- Stop awaiting the pool connection and just perform it internally as part of query

It also disables the slow-query warnings since that was a patch to node-mysql2 itself.

**Comment by akassl-lab** [comment]
Is the following commit a confirmed fixed?

https://github.com/overextended/oxmysql/commit/4e29905179698cac1a9fc5c6f9b6850c5ad75399

**Comment by thelindat** [comment]
It's unrelated, but still no repro. I'd recommend updating to latest optional build (or higher) of FXServer and latest oxmysql and seeing what happens.

**Comment by thelindat** [comment]
There has been no more reports of this issue, and I believe the stack trace bug was resolved on FXServer.
