### ISSUE TITLE
executeSync 

### ISSUE THREAD

**Issue by hoangpn** [overextended/oxmysql#76]
## Issue checklist

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Code**
```lua
  AddEventHandler('onResourceStart', function(ResourceName)
	-- get containers data when server resource started
	if ResourceName == 'iInventory' then
		-- containers data
		local Results = exports.oxmysql:executeSync('SELECT * FROM container')
		-- check results
		print(json.encode(Results))
	end
end)
```

**Expected behavior**

**Additional context**
- My script Working on 1.8.5, 1.8.6 **don't work**

**Server details**
- FXServer artifact

**Database details**
- MySQL
- 8

**Comment by thelindat** [comment]
Wow amazing, you've provided a whole lot of information for me to utilise here.

**Comment by QuickValve** [comment]
I think what he meant is, if the function is called before the oxmysql has established connection to database, the query didn't get executed, unlike on the previous version

**Comment by thelindat** [comment]
How do you figure that, based on the fact that he provided _zero information_?

Queries executed before oxmysql have started will delay their execution until the first tick. I literally just ran his snippet and it executes flawlessly.

**Comment by thelindat** [comment]
As usual I couldn't reproduce it. I'll try aimlessly shooting in the dark _again_, but try using `onServerResourceStart` rather than `onResourceStart`.

**Comment by QuickValve** [comment]
> Queries executed before oxmysql have started will delay their execution until the first tick. I literally just ran his snippet and it executes flawlessl

I also experienced problem maybe simmilar to his on the new version, the query didnt got executed if oxmysql havent made connection to database (even if the oxmysql resource status is started)

**Comment by hoangpn** [comment]
> > Queries executed before oxmysql have started will delay their execution until the first tick. I literally just ran his snippet and it executes flawlessl
> 
> I also experienced problem maybe simmilar to his on the new version, the query didnt got executed if oxmysql havent made connection to database (even if the oxmysql resource status is started). I tried downgrading to 1.8.5 and it works again
I downgraded and it worked, then i post this issue to community, i just try to using oxmysql in my framework, and my luck is my framework have two - five query only, it's easy for debug when facing issue

**Comment by thelindat** [comment]
[oxmysql.zip](https://github.com/overextended/oxmysql/files/7692023/oxmysql.zip)

Try using that, I've changed the promise to await resource state to be 'started'.

**Comment by hoangpn** [comment]
1.8.7 don't work in my case

**Comment by hoangpn** [comment]
> 1.8.7 don't work in my case

My mistake, 1.8.7 work with onResourceStart, confirmed
