### ISSUE TITLE
whats wrong here with 1.9.0 what i have to change?!

### ISSUE THREAD

**Issue by maxcamorra** [overextended/oxmysql#78]
## Issue checklist

- [X ] I am using the latest release
- [X ] I have referenced available documentation and cannot resolve the issue

**Describe the bug**
added the latest build now this happens:

**Screenshots**
![image](https://user-images.githubusercontent.com/78707245/147373935-4b4880ec-14b9-4e86-8a02-c21e3d5648c2.png)

**Comment by thelindat** [comment]
It says right here, oxmysql is stopped.

**Comment by maxcamorra** [comment]
hmm but why ? the server was running and oxmysql aswell :D

**Comment by thelindat** [comment]
I really don't know what to tell you; it says oxmysql is stopped, and that's not an inaccurate report.

1.9.0 has been tested with both the QB recipe and zap ESX recipe deployments, with zero alterations to the code.

**Comment by maxcamorra** [comment]
hmm ok i will try again

**Comment by maxcamorra** [comment]
ok it seems to work now but i get this error if a player tries to join
![image](https://user-images.githubusercontent.com/78707245/147393626-be2ffc77-68b9-46bb-87ef-488352a74a94.png)

**Comment by maxcamorra** [comment]
> ok it seems to work now but i get this error if a player tries to join ![image](https://user-images.githubusercontent.com/78707245/147393626-be2ffc77-68b9-46bb-87ef-488352a74a94.png)

![image](https://user-images.githubusercontent.com/78707245/147393629-2fbef7aa-b1a1-4afd-a47d-8786758c07b6.png)


This is the code

**Comment by thelindat** [comment]
If you still have your mysql-async folder, delete it.
