### ISSUE TITLE
TIMESTAMP return table not number.

### ISSUE THREAD

**Issue by chaixshot** [overextended/oxmysql#8]
Database **time** is TIMESTAMP type.
```
local result = "SELECT time AS time FROM phone_messages LIMIT 1"
print(result[1].time)
```
In mysql-async will get a float value `1631181159000.0` (GCPHONE sort sms data by this number.)
In oxmysql will get table data `table: 000001FE16562B60` (no value in for loop)
If set **mysql_connection_string "?dateStrings=true"** will get string `2021-09-09 16:52:39`

**Comment by IdrisDose** [comment]
For those who copy-paste form the documentation, you'll need to make it a `&dateStrings=true` instead of `?dateStrings=true` if you already have `?charset=utf8mb4`
