### ISSUE TITLE
Execute crashes when calling Procedures

### ISSUE THREAD

**Issue by Pawsative** [overextended/oxmysql#9]
Using MySQL Procedures with oxmysql:execute seems to just kill my server with no error logs or trace, tested with this procedure which works perfectly with ghmattimysql:

```
exports.oxmysql:execute("CALL `TropixRP_CreatePlayerData` (?, ?, ?, ?, ?, ?, ?)", {ID, SteamID, Discord, FirstName, LastName})
```
vs
```
exports.ghmattimysql:execute("CALL `TropixRP_CreatePlayerData` (@ID, @SteamID, @Discord, @FirstName, @LastName)",
    {
        ["@ID"] = ID,
        ["@SteamID"] = SteamID,
        ["@Discord"] = Discord,
        ["@FirstName"] = FirstName,
        ["@LastName"] = LastName,
    })
```

<img src="http://u.wsative.com/u/YIuxUN.png">

**Comment by dunak-debug** [comment]
So oxmysql `execute(...)` is calling `pool.execute(...)` under the hood and therefore mysql2 is attempting to **prepare** query, store it into cache and run it. Procedures can´t be passed into this method. 

In next update I will create another export `export.oxmysql:query(...)` which will call `pool.query(...)`. This export will be used for procedures and also for ex. queries that don´t need to be **stored into cache**.
