### ISSUE TITLE
prepare bug

### ISSUE THREAD

**Issue by WhatTheHellx2** [overextended/oxmysql#90]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
well based on the text on the doc `When using SELECT, the return value will match fetchAll, fetchSingle, or fetchScalar depending on the number of columns and rows selected.` its not returning all the rows ! it only return the first one even tho i have multiple row in that table 

**Screenshots**

**Code**
```lua
RegisterCommand("test" , function()
    MySQL.prepare('SELECT * FROM characters WHERE `identifier`= ?', { "steam:*********" }, function(users)
        print(ESX.DumpTable(users)) -- returns only 1 row
    end)
    MySQL.query('SELECT * FROM characters WHERE `identifier`= ?', { "steam:*********" }, function(users)
        print(ESX.DumpTable(users)) -- returns multiple row
    end)
end)
```

**Expected behavior**
prepare returns multiple row if there are any

**Additional context**

**Server details**
- FXServer artifact : v5365
- Operating system : w 10 pro (localhost)

**Database details**
- MariaDB or MySQL : Server version: 10.4.18-MariaDB
- Version : 10.4.18

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/commit/2d28c447ec7a1e6c1826c85ccb0075994a66ea5c
