### ISSUE TITLE
Execute "Cannot read properties of undefined"v 2.0.0 --> 2.0.2

### ISSUE THREAD

**Issue by NRTnarathip** [overextended/oxmysql#92]
## Issue checklist
- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [ ] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Error when SQL execute, update

error about "Cannot read properties of undefined"

**Expected behavior**
Error between version 2.0.0 ---> 2.0.2 latest
The condition that will cause an error is
update WHERE is have character : semi colon and
data set containing data " ' double or single quote such as json
Example 4 case error sql execute,update
UPDATE `users` SET `job` = ' " ' WHERE identifier 'license:xxxxxxxx'
UPDATE `users` SET `job` = '{ "himan" : 10 } ' WHERE identifier 'license:xxxxxxxx'
UPDATE `users` SET `job` = ' " ' WHERE identifier 'steam:'
UPDATE `users` SET `job` = ' ' ' WHERE identifier 'anyword:'
code 
![image](https://user-images.githubusercontent.com/61742272/155837641-cc022881-564d-41ca-b248-72a32ddcc529.png)

before execute
![image](https://user-images.githubusercontent.com/61742272/155837655-36364eb3-34ec-46f4-87c7-ae26685f9ef0.png)

after execute 
![image](https://user-images.githubusercontent.com/61742272/155837646-210ff1a3-038d-4a30-9966-5096eaa53930.png)
![image](https://user-images.githubusercontent.com/61742272/155837649-8784d8d9-d21b-4695-be84-6963a722a40f.png)

Example not error 
UPDATE `users` SET `job` = ' " ' WHERE identifier 'xxxxxxxx'
UPDATE `users` SET `job` = '{ "himan" : 10 } ' WHERE identifier 'xxxxxxxx'
UPDATE `users` SET `job` = ' ' ' WHERE identifier 'xxxxxxxx'
UPDATE `users` SET `job` = ' ' ' WHERE identifier 'anyword'
code 
![image](https://user-images.githubusercontent.com/61742272/155837592-f5190095-59ff-491d-aa7e-a108b056a9c1.png)

before execute 
![image](https://user-images.githubusercontent.com/61742272/155837595-6ac07cb0-6d74-4780-90ee-7835b3a12c7f.png)

after execute 
![image](https://user-images.githubusercontent.com/61742272/155837617-aa96487e-51bc-4acd-8887-211f2919b3e1.png)
![image](https://user-images.githubusercontent.com/61742272/155837624-1b2653f7-d5f0-4cfe-9046-1e5497ee4356.png)

Summary: Error when WHERE = " : " contains character text : semi colon and set data = ' " or ' ' single,double quote.

**Server details**
- FXServer artifact
- Win11

**Database details**
- MariaDB
- Version 8.0

**Comment by DokaDoka** [comment]
I hope your use of `string.format` here is just for demonstration, you should be using placeholders.

They are required for [prepare](https://overextended.github.io/oxmysql/usage/prepare/), but can and should be used with all queries where possible, they should probably have their own page in the docs.

Here's an example:
```lua
MySQL.update.await('UPDATE users SET ?? = ? WHERE identifier = ?', {'job', json.encode(data), license})
```
I believe this is the solution to your issues.

**Comment by NRTnarathip** [comment]
full code and you should try
use oxmysql v 2.0.0++
and set database like this
![image](https://user-images.githubusercontent.com/61742272/155841032-2dcf8fd2-567a-49ae-8907-dc4d457b6635.png)

```lua
function saveData()
    local saveData = {
        ["job"] = {
            ["himan"] = 10,
            ["wowo"] = 20,
        }, 
        ["inventory"] = "Hello"
    }
    local myLicense = "license:123123"
    local states_data, first = "", true
    for state_name, state in pairs(saveData) do
        if type(state) == "table" then state = json.encode(state) end
        if not first then states_data = states_data ..", " end
        first = false
        states_data = states_data .. string.format("`%s` = '%s'", state_name, state)
    end
    local database_query = string.format("UPDATE `users` SET %s WHERE identifier = '%s'", states_data, myLicense)
    MySQL.Sync.execute(database_query)
end
```

**Comment by NRTnarathip** [comment]
test: v2.0.+
will you get issues like this
![image](https://user-images.githubusercontent.com/61742272/155841160-ffb20120-b460-4764-b04a-46bbd3d24259.png)
test: v 1.9.3 it no problem
work everyting func mysql
![image](https://user-images.githubusercontent.com/61742272/155841183-b56b718d-5b76-43d4-8387-9c07631d49ee.png)

**Comment by NRTnarathip** [comment]
![image](https://user-images.githubusercontent.com/61742272/155841225-760b976a-5881-4428-9e96-3d5fade3a7f2.png)
it keyword "Cannot read properties of undefined"

**Comment by NRTnarathip** [comment]
i believe you can do it✌️✌️

**Comment by thelindat** [comment]
Why the fuck are you spamming out posts and weird comments? Yes it’s a bug and it’ll be resolved, however you _shouldn’t_ write your queries in such fucked ways in the first place.

**Comment by NRTnarathip** [comment]
ok sorry bro, i tried to report the problem and fixed this bug for a very long time
I'll close this post issue, thanks bro.
and im not good at english🙏
