### ISSUE TITLE
Fetch, etc. I want to know how to replace the code that was removed because it was not used before.

### ISSUE THREAD

**Issue by lukehemmin** [overextended/oxmysql#93]
First, the sentence may be strange using a translator. I'm sorry.

I tried to apply the previous script to the FiveM server, but there was an error, so I was confused. When I looked up this and that, I found out that it was a SQL-related problem.
So I found Documentation, modified this and that, and modified it. I think it will be difficult to solve this problem with my head. I'm here to find people smarter than me. Can you help me?

https://github.com/Virus18sp/truck_logistics/blob/main/truck_logistics/server.lua

**Comment by thelindat** [comment]
Add '@oxmysql/lib/MySQL.lua' to the top of `server_scripts` in `fxmanifest.lua`.

fetch is MySQL.query, fetchSync is MySQL.query.await. Refer to the docs for more.

**Comment by lukehemmin** [comment]
![image](https://user-images.githubusercontent.com/45535388/156009258-bad66a86-bb43-49e0-8a51-d7ec0973e6de.png)

**Comment by 0xDEMXN** [comment]
> ![image](https://user-images.githubusercontent.com/45535388/156009258-bad66a86-bb43-49e0-8a51-d7ec0973e6de.png)

Make sure you're using the release and not source code

**Comment by lukehemmin** [comment]
https://github.com/Virus18sp/truck_logistics/tree/main/truck_logistics

I don't think there's a separate release.

**Comment by 0xDEMXN** [comment]
> https://github.com/Virus18sp/truck_logistics/tree/main/truck_logistics
> 
> 
> 
> I don't think there's a separate release.

I was talking about oxmysql, however I see that the resource is using exports, you should convert them to the new aliases.

**Comment by lukehemmin** [comment]
Then what should I fix? Export? It's my first time doing this, so I don't know what to do. 😭

**Comment by thelindat** [comment]
Look at docs, we're not going to rewrite the syntax a 10th time.
