### ISSUE TITLE
 SCRIPT ERROR in promise (unhandled): TypeError: Cannot read properties of undefined (reading 'getConnection')

### ISSUE THREAD

**Issue by Zaickz** [overextended/oxmysql#94]
- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
After the update to 2.0.3 i have the following error, but the DB connection seems to be established correctly.

**Code**
set mysql_connection_string "mysql://user:pw@localhost/redm_test?charset=utf8mb4"
```
    [      script:oxmysql] SCRIPT ERROR in promise (unhandled): TypeError: Cannot read properties of undefined (reading 'getConnection')
[      script:oxmysql] > rawTransaction (@oxmysql/dist/build.js:21729)
[      script:oxmysql] > Object.callback (@oxmysql/dist/build.js:21839)
[      script:oxmysql] 
.
.
.
. 
[      script:oxmysql] Database server connection established!
```

**Server details**
- FXServer artifact 5327
- Operating system Linux Debian 11

**Database details**
- MariaDB 
- Version 10.6.5

**Comment by thelindat** [comment]
Transactions executed during the first server tick were triggering before the connection pool was established. Fixed.

**Comment by RenggoStarz** [comment]
how to fix this problem 
[      script:oxmysql] SCRIPT ERROR in promise (unhandled): Error: Query expected a string but received object instead
[      script:oxmysql] > parseArguments (@oxmysql/dist/build.js:21554)
[      script:oxmysql] > rawQuery (@oxmysql/dist/build.js:21709)
[      script:oxmysql]
