### ISSUE TITLE
Connection Access Denied

### ISSUE THREAD

**Issue by mat945** [overextended/oxmysql#98]
Hey, i got this error when i put my sql on the server : 

![Sans titre](https://user-images.githubusercontent.com/31307122/157070810-b945c580-baa5-4203-941a-9a03d4d9b26d.png)

i have special character on my password and am in Pterodactyl server.

This is my base mysql_connection_string : 
set mysql_connection_string "user=DBUSERNAME;database=DBNAME;password=DBPASSWORD;ip=DBIP;charset=utf8mb4"

**Comment by thelindat** [comment]
> Pterodactyl 

There's your problem.
