### ISSUE TITLE
No support for Pterodactyl

### ISSUE THREAD

**Issue by thelindat** [overextended/oxmysql#99]
To quote txAdmin
> Those setups are weird and not recommended, your problem.

**Comment by avery1227** [comment]
For future reference for people using Pterodactyl. You are able to change this line of code to generate passwords without the characters.

https://github.com/pterodactyl/panel/blob/f973285e04556e08607ba5cd56bb751c29082cf9/app/Helpers/Utilities.php#L24

**Comment by thelindat** [comment]
> Where is the problem with pterodactyl? We'r using oxmysql and pterodactyl just fine...
> 
> ```
> set mysql_connection_string "user=uxx_xxxx;host=xxxxx;database=xxxx;password=iqJ0xxxx^frxxu@gJp!Fnxxx;charset=utf8mb4"
> ```
> 
> (x = masked)
> 
> //EDIT: Okay, i updated on our test server from 1.8.0 to the latest 2.x version and the error appeared.. mhh...
> 
> Or is there another issue?

Pterodactyl has literally always been a pain in the arse, with you yourself experiencing issues that turned Pterodactyl into a meme on our Discord server.


Generally the issue is just password related, but since 90% of people asking for support haven’t the slightest idea how networking works (see: wrong up displays in connection error) it just isn’t worth our time offering support to people using this container.

**Comment by Twinkiees** [comment]
![image](https://user-images.githubusercontent.com/65138891/160259792-80421914-1605-495d-8268-26211c4c5ea8.png)

**Comment by thelindat** [comment]
> ![image](https://user-images.githubusercontent.com/65138891/160259792-80421914-1605-495d-8268-26211c4c5ea8.png)

Have you considered the possibility that your brain is much too small to comprehend the complex intricacies of downloading a resource, and thus running a server _might not be the right fit for you_?
